objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>This value will be set based on the IMCD Company of your User.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ImcdBusinessUnit__c</fullName>
        <description>Stores the Business Unit, dependant on the Company.</description>
        <label>IMCD Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDBusinessUnit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntegrationId__c</fullName>
        <externalId>true</externalId>
        <label>IntegrationId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LocalErpId__c</fullName>
        <description>Field storing External Unique Id from a non-group ERP system</description>
        <externalId>true</externalId>
        <label>Local ERP Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LockedForIntegration__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating when a Prospect has been sent for Integration. When Checkbox is set, Validation rules define update behavior on certain fields.</description>
        <inlineHelpText>When this box is checked, the record is locked and certain fields cannot be edited</inlineHelpText>
        <label>Locked for Integration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_LOB1__c</fullName>
        <label>Primary LOB1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SfManagedAccount__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field when set means the Account was created by a user with the SfManagedAccounts permission. It means the Account has not been integrated and is managed from within Salesforce only.</description>
        <label>SF-Managed Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Not Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isValidShipping__c</fullName>
        <formula>AND ( 
    NOT ( ISBLANK ( ShippingStreet ) )
    , NOT ( ISBLANK ( ShippingPostalCode ) )  
    , NOT ( ISBLANK ( ShippingCity ) )
    , NOT ( ISBLANK ( ShippingCountry ) )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valid Main Address</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ImcdCompany__c.object
<CustomObject>
    <description>Custom Object used to store data specific to each IMCD company (see the IMCD global picklist). It is used (not only) for quote document generation purpose. It is related to user.</description>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <label>IMCD Company</label>
    <nameField>
        <label>IMCD Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMCD Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/IntegrationLog__c.object
<CustomObject>
    <description>This object stores records which require integration. The object triggers in turn Outbound Messages when required. The object also acts as mechanism to track records requiring ETL-based integrations for non-group ERP countries.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Integration Logs</relationshipLabel>
        <relationshipName>Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Field storing the type of integration event such as &quot;Create Account&quot;, &quot;Create Principal&quot;, &quot;Create Price&quot;.</description>
        <label>Event</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <formula>IF ( !ISBLANK(Product__r.Id), TEXT(Product__r.CreatedBy.ImcdCompany__c),
			IF ( !ISBLANK(ContractedPrice__r.Id), TEXT(ContractedPrice__r.SBQQ__Account__r.IMCDCompany__c),
						IF ( !ISBLANK(Case__r.Id), TEXT(Case__r.Account.IMCDCompany__c),
         IF ( !ISBLANK(Account__r.Id), TEXT(Account__r.IMCDCompany__c), &apos;Undefined&apos;
							  )
      )
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IMCD Company</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntegrationId__c</fullName>
        <description>This fields contains the IntegrationId__c from the triggering record, if available. This field will be null for new records.</description>
        <label>Integration Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Queued is the initial status. When the Workflow has submitted the Outbound message the status will be set to Message Triggered. Message Delivered will be updated by Talend once the Outbound message is received and queued on the ESB but before being processed. Integration Completed is updated by Talend or the status is set to Integration Failed. Delivery Failed is updated by Salesforce in case a record remained Queued for &gt; 24 hours.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                    <default>true</default>
                    <label>Queued</label>
                </value>
                <value>
                    <fullName>Message Triggered</fullName>
                </value>
                <value>
                    <fullName>Message Delivered</fullName>
                </value>
                <value>
                    <fullName>Integration Completed</fullName>
                </value>
                <value>
                    <fullName>Integration Failed</fullName>
                </value>
                <value>
                    <fullName>Delivery Failed</fullName>
                </value>
                <value>
                    <fullName>Integration Completed (Country not Active)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>INT{000000000}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IntegrationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings and constants for Integration such as Events etc.</description>
    <fields>
        <fullName>EvtCreateSoldTo__c</fullName>
        <label>Create Customer (Sold-to) Event</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Integration Settings</label>
</CustomObject>

globalValueSets/LOB1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advanced Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Coatings &amp; Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Food</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care and I&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Lubricants</fullName>
    </customValue>
    <customValue>
        <fullName>Other Specialties</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Care</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmaceuticals</fullName>
    </customValue>
    <customValue>
        <fullName>Synthesis</fullName>
    </customValue>
    <masterLabel>LOB1</masterLabel>
</GlobalValueSet>

classes/SubmitProspectController.cls
/*------------------------------------------------------------	
Author:        Jeroen Burgers	
Company:       Salesforce	
Description:   Class supporting the SubmitProspectComp.cmp
Inputs:        ID of the triggering Account record	
Test Class:    TestSubmitProspectController	
History	
03/28/2018	   Created class
04/10/2018     SF/JEBU/Implemented SFDP-1512
22/01/2019	   SF/MICO/Including ImcdBusinessUnit__c required prior to Submit the prospect 	(SFDP-2025)
------------------------------------------------------------*/	

public class SubmitProspectController {

	/*------------------------------------------------------------
	Description:   Aura enabled method, invoked from SubmitProspectComp
	Inputs:        ID of the triggering Account record
	Functionality: Get basic data needed for the SubmitProspectComp.
	Return value:  Map of Objects
	History
		05/10/2018	   SF/JEBU/Created Method (part of SFDP-1512) -- refactoring
	------------------------------------------------------------*/
	@AuraEnabled
	public static Map<String, Object> getData (ID recordId) {
		Map <String, Object> data = new Map<String, Object>();
		Account prospect = getProspect(recordId);
		data.put('Id', prospect.Id);
		data.put('Primary_LOB1__c', prospect.Primary_LOB1__c);
		data.put('LockedForIntegration__c', prospect.LockedForIntegration__c);
		data.put('isValidShipping__c', prospect.isValidShipping__c);
        data.put('ImcdBusinessUnit__c', prospect.ImcdBusinessUnit__c);
		data.put('hasActiveIntegration', hasActiveIntegration(recordId));
		data.put('sfManagedAccounts', checkPermission('SfManagedAccounts'));
		return data;
	}

	private static Account getProspect (ID recordId) {
		return ([SELECT Id, Primary_LOB1__c, LockedForIntegration__c, isValidShipping__c, ImcdBusinessUnit__c FROM Account WHERE id = :recordId]);
    }
    
    /*
    * Method checking if there is a record in the IntegrationLog__c indicating an active integration
    */
    @AuraEnabled
	public static Boolean hasActiveIntegration (ID recordId) {
        return ([SELECT Id FROM IntegrationLog__c WHERE Account__c = :recordId AND Status__c IN ('Queued', 'Message Triggered', 'Message Delivered')].size() > 0);
    }
    
    /*------------------------------------------------------------	
	Description:   Aura enabled method, invoked from SubmitProspect.cmp
	Inputs:        ID of the triggering Account record	
	Functionality: Created IntegrationLog__c (transaction) including exception handling
	Return value:  Boolean, true indicating success. 
	History	
	03/30/2018	   Created Method
	------------------------------------------------------------*/	
    @AuraEnabled
	public static Boolean integrateProspect (ID recordId, String integrationId) {
	    if (!checkPermission('SfManagedAccounts')) return createIntegrationLog(recordId);
	    else return convertSoldtoAccount(recordId, integrationId);
    }

	private static Boolean checkPermission(String permission) {
		return FeatureManagement.checkPermission(permission);
	}

	@TestVisible
	private static Boolean convertSoldtoAccount(ID recordId, String integrationId) {
		Account accnt = [SELECT Id, RecordTypeId, IMCDCompany__c FROM Account WHERE Id = :recordId LIMIT 1];
		accnt.RecordTypeId = IMCDUtils.getRecordType(Label.Account_object_Name, Label.Customer_Sold_To_Account_Record_Type).Id;
		accnt.SfManagedAccount__c = true;
		accnt.IntegrationId__c = integrationId;
		accnt.LocalErpId__c = integrationId + '__' + accnt.IMCDCompany__c;

		// Savepoint to rollback
		Savepoint sp = Database.setSavepoint();
		Database.SaveResult srAccnt = Database.update(accnt, false);

		// Error handling
		if (srAccnt.isSuccess())
			return true;
		else {
			Database.rollback(sp);
			logSrError(srAccnt);
			return false;
		}
	}

	@TestVisible
	private static Boolean createIntegrationLog(ID recordId) {
		Boolean result = false;
		String event = IntegrationSettings__c.getInstance(UserInfo.getUserId()).EvtCreateSoldTo__c;
		Account accnt = [SELECT Id, LockedForIntegration__c FROM Account WHERE Id =: recordId LIMIT 1];

		IntegrationLog__c lstIntLog = new IntegrationLog__c (Account__c = recordId, Status__c = 'Queued', Event__c = event);

		// Added for Test coverage, provoke DML exceptions
		if (Test.isRunningTest() && accnt.LockedForIntegration__c == true)
			lstIntLog.Status__c = 'SETTING_UP_FOR_DML_FAILURE';

		accnt.LockedForIntegration__c = true;

		// Savepoint to rollback
		Savepoint sp = Database.setSavepoint();
		Database.SaveResult srInt = Database.insert(lstIntLog, false);
		Database.SaveResult srAccnt = Database.update(accnt, false);

		// Error handling
		if (srInt.isSuccess() && srAccnt.isSuccess()) result = true;
		// Rollback?
		if (!result) Database.rollback(sp); else return result;

		if (!srInt.isSuccess()) logSrError(srInt);
		if (!srAccnt.isSuccess()) logSrError(srAccnt);

		return result;
	}
                              
	private static void logSrError(Database.SaveResult sr) {
		for(Database.Error err : sr.getErrors()) {
			DebugLog.addError('[SubmitProspectController][integrateProspect] An error has occurred.\n'
                              + err.getStatusCode() + ': ' + err.getMessage() + '\n'
                              + 'Fields affected: ' + + err.getFields());
		}                              
	}
 }