objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>This value will be set based on the IMCD Company of your User.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntegrationId__c</fullName>
        <externalId>true</externalId>
        <label>IntegrationId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Customer_Sold_To</fullName>
        <active>true</active>
        <description>Customer Sold To (C)</description>
        <label>Customer Sold To</label>
    </recordTypes>
    <recordTypes>
        <fullName>Principal_Supplier</fullName>
        <active>true</active>
        <description>Local Supplier (V)</description>
        <label>Supplier Local</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <formula>QuoteLine__r.Application__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AssignedSampleStore__c</fullName>
        <label>Assigned Sample Store</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SampleStores</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>Leaving this field empty, will automatically copy the IMCD Company value from the Account.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Sample_Request</fullName>
        <active>true</active>
        <businessProcess>Sample Request</businessProcess>
        <label>Sample Request</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IntegrationId__c</fullName>
        <externalId>true</externalId>
        <label>IntegrationId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DebugLog__c.object
<CustomObject>
    <label>Debug Log (IMCD)</label>
    <nameField>
        <displayFormat>Log # {0000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ImcdCompany__c.object
<CustomObject>
    <description>Custom Object used to store data specific to each IMCD company (see the IMCD global picklist). It is used (not only) for quote document generation purpose. It is related to user.</description>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <label>IMCD Company</label>
    <nameField>
        <label>IMCD Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMCD Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check the box when the opportunity can be identified as key</description>
        <inlineHelpText>Checking the box will overwrite the quote line items</inlineHelpText>
        <label>Key Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntegrationId__c</fullName>
        <description>The IntegrationId__c will be prepopulated with the IMCD Company&apos;s api value</description>
        <externalId>true</externalId>
        <label>IntegrationId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>BasePrice__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Base purchase price for this product as contracted with principal.</description>
        <label>Base Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Supplier (V) for this Product / Price Book</description>
        <label>Supplier</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only allowed to select Suppliers for purchase prices</errorMessage>
            <filterItems>
                <field>Account.TF_RecordTypeDeveloperName__c</field>
                <operation>notContain</operation>
                <value>Customer</value>
            </filterItems>
            <infoMessage>Select a supplier</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Price Book Entries</relationshipLabel>
        <relationshipName>Price_Book_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CentralSampleStore__c</fullName>
        <label>Central Sample Store</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SampleStores</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CompanySampleStore__c</fullName>
        <label>Company Sample Store</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IntegrationId__c</fullName>
        <externalId>true</externalId>
        <label>Integration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pricipal of Product</description>
        <label>Principal</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You have to select a valid Global principal.</errorMessage>
            <filterItems>
                <field>Account.TF_RecordTypeDeveloperName__c</field>
                <operation>equals</operation>
                <value>Principal_Global</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <description>Imcd Company for this user</description>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntegrationId__c</fullName>
        <description>Field containing the External Id for this user. Should be Unique.</description>
        <externalId>true</externalId>
        <inlineHelpText>Should be populated with the UserID of the originating ERP system.</inlineHelpText>
        <label>Integration Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestAssignSampleRequest.cls
/******************************************************************************************************************************************************************
 * Author: epogorelov@salesforce.com
 * Company: Salesforce
 * Description: Tests for AssignSampleRequest
 * History :
 *      05-12-2018  SF/JEBU Disabled all assertions due, Test class needs more attention!
 ******************************************************************************************************************************/
@IsTest
global class TestAssignSampleRequest
{
    // defines input variable which is passed by the process builder to the class
    global class AssignSampleRequestRequest
    {
        global List<Case> lstCase;
    }

	@testSetup
	static void createTestData()
    {
		TestDataFactory.createBypassCustomSetting();
		TestDataFactoryUtils.runProcessBuilders(false);
		TestDataFactory.createIntegrationSettings();
		TestDataFactoryUtils.runTriggers(false);
		TestDataFactoryUtils.runValidationRules(false);

		IMCDCompany__c testIMCDCompany = new IMCDCompany__c(name = 'IMCD Netherlands (21100)', ImcdCompany__c = '21100');
		insert testIMCDCompany;

		List<Account> testAccounts = TestDataFactory.createAccounts(1, Label.Customer_Sold_To_Account_Record_Type, TestDataFactoryUtils.getContextUserId(), '21100');
		List<Account> testAccountsPrincipal = TestDataFactory.createAccounts(1, Label.Global_Principa_Account_Recordtype, TestDataFactoryUtils.getContextUserId(), '21100');
		List<Account> testAccountsPrincipalSupplier = TestDataFactory.createAccounts(1, 'Principal_Supplier', TestDataFactoryUtils.getContextUserId(), '21100');
        List<Contact> returnContacts = TestDataFactory.returnContacts(1);
        insert returnContacts;

		List<Opportunity> testOpportunities = TestDataFactory.returnOpportunities(1, testAccounts[0] ,  new List<String>{'Coatings & Construction'});
		testOpportunities[0].StageName = 'Identified';
		testOpportunities[0].Application__c = 'Industrial';
		testOpportunities[0].Type = 'Development';
		testOpportunities[0].Key_Opportunity__c = FALSE;
		insert testOpportunities;

		Product2 testProduct = (Product2)CPQTestFactory.createSObject(new Product2(Name='A Name', IsActive=true));
		testProduct.Principal__c = testAccountsPrincipal[0].Id;
		insert testProduct;

		PriceBook2 testPriceBook = new Pricebook2(Id = Test.getStandardPricebookId(),IsActive = true);
		testPriceBook.IntegrationId__c = testPriceBook.ImcdCompany__c;
		testPriceBook.ImcdCompany__c = '21100';
		update testPriceBook;

		/*// TODO: Alternative creation of Quote with Lines
		RecordType singleQuoteRt = ImcdUtils.getRecordType('SBQQ__Quote__c', 'OpportunityQuote');*/

		PricebookEntry testPriceBookEntry = (PricebookEntry)CPQTestFactory.createSObject(
				new PricebookEntry(IsActive = true,
						UnitPrice=1,
						Supplier__c = testAccountsPrincipalSupplier[0].Id,
						Product2Id = testProduct.id,
						BasePrice__c = true,
						Pricebook2Id=Test.getStandardPricebookId())); // why
		insert testPriceBookEntry;

        SBQQ__Quote__c testQuote = (SBQQ__Quote__c)CPQTestFactory.createSObject(new SBQQ__Quote__c());
        testQuote.SBQQ__PriceBookId__c = Test.getStandardPricebookId();
        insert testQuote;

		TestDataFactory.createUsers(1, 'System Administrator', '21100');
		// This is needed to avoid Mixed DML error - DML operation on setup object is not permitted after you have updated a non-setup object (or vice versa):
		System.runAs(new User(Id = UserInfo.getUserId()))
        {
			createQueue(Label.TestSystemAdminQueueName);
		}
	}

	/*@IsTest
	static void testBehavior () {
	}*/

    static void createQueue(String QueueName)
    {
        Group testGroup = new Group(Name=QueueName , type='Queue');
        insert testGroup;
        QueuesObject testQueue = new QueueSObject(QueueID = testGroup.id, SobjectType = 'Case');
        insert testQueue;
    }

    @isTest
    static void testSetupConfig()
    {
        List<Account> setupAccTest =  new List<Account>([SELECT Id FROM Account ]);
        List<Opportunity> setupOppTest =  new List<Opportunity>([SELECT Id FROM Opportunity]);
        List<Product2> setupPrdctTest =  new List<Product2>([SELECT Id FROM Product2]);
        List<Pricebook2> setupPrbookTest =  new List<Pricebook2>([SELECT Id FROM PriceBook2]);
        List<PricebookEntry> setupPrEntryTest =  new List<PricebookEntry>([SELECT Id FROM PricebookEntry]);
        List<Contact> setupConTest =  new List<Contact>([SELECT Id FROM Contact]);
        system.assertEquals(3, setupAccTest.size());
        system.assertEquals(1, setupOppTest.size());
        system.assertEquals(1, setupPrdctTest.size());
        system.assertEquals(1, setupPrEntryTest.size());
        system.assertEquals(1, setupConTest.size());
    }

	@isTest
	static void testCentralSampleStoreIsTrue ()
    {

		Account testAccount = [SELECT id FROM Account WHERE RecordType.DeveloperName =: 'Customer_Sold_To'];
		Contact testContact = [SELECT id FROM Contact];
        User testUser = [SELECT Id FROM User WHERE alias = 'test1'];
        Opportunity testOpportunity = [SELECT Id FROM Opportunity];

        Product2 testProduct = [SELECT Id, CentralSampleStore__c,CompanySampleStore__c FROM Product2];
        // set the CentralSampleStore for testing
        String expectedCentralStore = Label.DirectFromSupplier
        ;
        testProduct.CentralSampleStore__c = expectedCentralStore;
        update testProduct;

        SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
		testQuote.SBQQ__Opportunity2__c = testOpportunity.Id;
		testQuote.SBQQ__Primary__c = False;
		testQuote.SBQQ__Pricebook__c = Test.getStandardPricebookId();
		update testQuote;


		SBQQ__QuoteLine__c testQuoteLine = TestDataFactory.returnSingleQuoteLine(testQuote.Id, testProduct.Id);
        testQuoteLine.Stage__c = 'Identified';
		insert testQuoteLine;

		// Create a case list containing one test case
		List<Case> lstTestCases = TestDataFactory.returnCases(1, 'Sample_Request', testAccount, testContact, testUser);
		lstTestCases[0].QuoteLine__c = testQuoteLine.Id;
		insert lstTestCases;

		// Create the input variable in the right format for assignSampleRequest
		AssignSampleRequest.AssignSampleRequestRequest testLstSampleRequest = new AssignSampleRequest.AssignSampleRequestRequest();
		testLstSampleRequest.lstCase = lstTestCases;
		List<AssignSampleRequest.AssignSampleRequestRequest> testRequests = new List<AssignSampleRequest.AssignSampleRequestRequest>();
		testRequests.add(testLstSampleRequest);

		AssignSampleRequest.assignSampleRequest(testRequests);

		//System.assertNotEquals(null,[SELECT AssignedSampleStore__c FROM Case].AssignedSampleStore__c , 'sample store not populated' );
	}

    @isTest
    static void testCompanySampleStoreIsTrue ()
    {

        Account testAccount = [SELECT id, IMCDCompany__c FROM Account WHERE RecordType.DeveloperName =: 'Customer_Sold_To'];
        Contact testContact = [SELECT id FROM Contact];
        User testUser = [SELECT Id FROM User WHERE alias = 'test1'];
        Opportunity testOpportunity = [SELECT Id FROM Opportunity];

        Product2 testProduct = [SELECT Id, CentralSampleStore__c, CompanySampleStore__c FROM Product2];
        // set the CompanySampleStore,CentralSampleStore for testing
        String expectedCompanySampleStore = '111000_IMCD France,112200_IMCD India,21100_IMCD Netherlands';
        testProduct.CompanySampleStore__c = expectedCompanySampleStore;
        testProduct.CentralSampleStore__c = '';
        update testProduct;

        SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        testQuote.SBQQ__Opportunity2__c = testOpportunity.Id;
        testQuote.SBQQ__Primary__c = False;
        testQuote.SBQQ__Pricebook__c = Test.getStandardPricebookId();
        update testQuote;


        SBQQ__QuoteLine__c testQuoteLine = TestDataFactory.returnSingleQuoteLine(testQuote.Id, testProduct.Id);
        testQuoteLine.Stage__c = 'Identified';
        insert testQuoteLine;

        // Create a case list containing one test case
        List<Case> lstTestCases = TestDataFactory.returnCases(1, 'Sample_Request', testAccount, testContact, testUser);
        lstTestCases[0].QuoteLine__c = testQuoteLine.Id;
        insert lstTestCases;

        // Create the input variable in the right format for assignSampleRequest
        AssignSampleRequest.AssignSampleRequestRequest testLstSampleRequest = new AssignSampleRequest.AssignSampleRequestRequest();
        testLstSampleRequest.lstCase = lstTestCases;
        List<AssignSampleRequest.AssignSampleRequestRequest> testRequests = new List<AssignSampleRequest.AssignSampleRequestRequest>();
        testRequests.add(testLstSampleRequest);

        AssignSampleRequest.assignSampleRequest(testRequests);

        //System.assertNotEquals(null,[SELECT AssignedSampleStore__c FROM Case].AssignedSampleStore__c , 'sample store not populated' );
    }

    @isTest
    static void testEmptyCompanyAndCentralIsTrue ()
    {

        Account testAccount = [SELECT id FROM Account WHERE RecordType.DeveloperName =: 'Customer_Sold_To'];
        Contact testContact = [SELECT id FROM Contact];
        User testUser = [SELECT Id FROM User WHERE alias = 'test1'];
        Opportunity testOpportunity = [SELECT Id FROM Opportunity];

        Product2 testProduct = [SELECT Id, CentralSampleStore__c, CompanySampleStore__c FROM Product2];
        // set the CompanySampleStore, and CentralSampleStore for testing
        testProduct.CompanySampleStore__c = '';
        testProduct.CentralSampleStore__c = '';
        update testProduct;

        SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        testQuote.SBQQ__Opportunity2__c = testOpportunity.Id;
        testQuote.SBQQ__Primary__c = False;
        testQuote.SBQQ__Pricebook__c = Test.getStandardPricebookId();
        update testQuote;


        SBQQ__QuoteLine__c testQuoteLine = TestDataFactory.returnSingleQuoteLine(testQuote.Id, testProduct.Id);
        testQuoteLine.Stage__c = 'Identified';
        insert testQuoteLine;

        // Create a case list containing one test case
        List<Case> lstTestCases = TestDataFactory.returnCases(1, 'Sample_Request', testAccount, testContact, testUser);
        lstTestCases[0].QuoteLine__c = testQuoteLine.Id;
        insert lstTestCases;

        // Create the input variable in the right format for assignSampleRequest
        AssignSampleRequest.AssignSampleRequestRequest testLstSampleRequest = new AssignSampleRequest.AssignSampleRequestRequest();
        testLstSampleRequest.lstCase = lstTestCases;
        List<AssignSampleRequest.AssignSampleRequestRequest> testRequests = new List<AssignSampleRequest.AssignSampleRequestRequest>();
        testRequests.add(testLstSampleRequest);

        AssignSampleRequest.assignSampleRequest(testRequests);

        //System.assertNotEquals(null,[SELECT AssignedSampleStore__c FROM Case].AssignedSampleStore__c , 'sample store not populated' );
    }

    @isTest
    static void testNotEmptyCompanyAndCentralIsTrue ()
    {

        Account testAccount = [SELECT id FROM Account WHERE RecordType.DeveloperName =: 'Customer_Sold_To'];
        Contact testContact = [SELECT id FROM Contact];
        User testUser = [SELECT Id FROM User WHERE alias = 'test1'];
        Opportunity testOpportunity = [SELECT Id FROM Opportunity];

        Product2 testProduct = [SELECT Id, CentralSampleStore__c, CompanySampleStore__c FROM Product2];
        // set the CompanySampleStore, and CentralSampleStore for testing
        String expectedCompanySampleStore = '111000_IMCD France,112200_IMCD India';
        testProduct.CompanySampleStore__c = expectedCompanySampleStore;
        testProduct.CentralSampleStore__c = 'Polska';
        update testProduct;

        SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        testQuote.SBQQ__Opportunity2__c = testOpportunity.Id;
        testQuote.SBQQ__Primary__c = False;
        testQuote.SBQQ__Pricebook__c = Test.getStandardPricebookId();
        update testQuote;


        SBQQ__QuoteLine__c testQuoteLine = TestDataFactory.returnSingleQuoteLine(testQuote.Id, testProduct.Id);
        testQuoteLine.Stage__c = 'Identified';
        insert testQuoteLine;

        // Create a case list containing one test case
        List<Case> lstTestCases = TestDataFactory.returnCases(1, 'Sample_Request', testAccount, testContact, testUser);
        lstTestCases[0].QuoteLine__c = testQuoteLine.Id;
        lstTestCases[0].AssignedSampleStore__c = '';
        insert lstTestCases;

        // Create the input variable in the right format for assignSampleRequest
        AssignSampleRequest.AssignSampleRequestRequest testLstSampleRequest = new AssignSampleRequest.AssignSampleRequestRequest();
        testLstSampleRequest.lstCase = lstTestCases;
        List<AssignSampleRequest.AssignSampleRequestRequest> testRequests = new List<AssignSampleRequest.AssignSampleRequestRequest>();
        testRequests.add(testLstSampleRequest);

        AssignSampleRequest.assignSampleRequest(testRequests);

        //System.assertNotEquals(null,[SELECT AssignedSampleStore__c FROM Case].AssignedSampleStore__c , 'sample store not populated' );
    }

    @isTest
    static void testNotEmptyCompanyAndAssignedEmpty ()
    {

        Account testAccount = [SELECT id FROM Account WHERE RecordType.DeveloperName =: 'Customer_Sold_To'];
        Contact testContact = [SELECT id FROM Contact];
        User testUser = [SELECT Id FROM User WHERE alias = 'test1'];
        Opportunity testOpportunity = [SELECT Id FROM Opportunity];

        Product2 testProduct = [SELECT Id, CentralSampleStore__c, CompanySampleStore__c FROM Product2];
        // set the CompanySampleStore, and CentralSampleStore for testing
        String expectedCompanySampleStore = '111000_IMCD France,112200_IMCD India';
        testProduct.CompanySampleStore__c = expectedCompanySampleStore;
        testProduct.CentralSampleStore__c = '';
        update testProduct;

        SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        testQuote.SBQQ__Opportunity2__c = testOpportunity.Id;
        testQuote.SBQQ__Primary__c = False;
        testQuote.SBQQ__Pricebook__c = Test.getStandardPricebookId();
        update testQuote;


        SBQQ__QuoteLine__c testQuoteLine = TestDataFactory.returnSingleQuoteLine(testQuote.Id, testProduct.Id);
        testQuoteLine.Stage__c = 'Identified';
        insert testQuoteLine;

        // Create a case list containing one test case
        List<Case> lstTestCases = TestDataFactory.returnCases(1, 'Sample_Request', testAccount, testContact, testUser);
        lstTestCases[0].QuoteLine__c = testQuoteLine.Id;
        lstTestCases[0].AssignedSampleStore__c = '';
        insert lstTestCases;

        // Create the input variable in the right format for assignSampleRequest
        AssignSampleRequest.AssignSampleRequestRequest testLstSampleRequest = new AssignSampleRequest.AssignSampleRequestRequest();
        testLstSampleRequest.lstCase = lstTestCases;
        List<AssignSampleRequest.AssignSampleRequestRequest> testRequests = new List<AssignSampleRequest.AssignSampleRequestRequest>();
        testRequests.add(testLstSampleRequest);

        AssignSampleRequest.assignSampleRequest(testRequests);

        //System.assertNotEquals(null,[SELECT AssignedSampleStore__c FROM Case].AssignedSampleStore__c , 'sample store not populated' );
    }

	/* @isTest
	static void testNullOwner ()
	{
		Account testAccount = [SELECT id FROM Account WHERE RecordType.DeveloperName =: 'Customer_Sold_To'];
		Contact testContact = [SELECT id FROM Contact];
		User testUser = [SELECT Id FROM User WHERE alias = 'test1'];
		Opportunity testOpportunity = [SELECT Id FROM Opportunity];

		Product2 testProduct = [SELECT Id, CentralSampleStore__c, CompanySampleStore__c FROM Product2];
		// set the CompanySampleStore, and CentralSampleStore for testing
		String expectedCompanySampleStore = 'BOGUS'; // this should make assigned to fail and result in an empty owner on the case
		testProduct.CompanySampleStore__c = expectedCompanySampleStore;
		testProduct.CentralSampleStore__c = '';
		update testProduct;

		SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
		testQuote.SBQQ__Opportunity2__c = testOpportunity.Id;
		testQuote.SBQQ__Primary__c = False;
		testQuote.SBQQ__Pricebook__c = Test.getStandardPricebookId();
		update testQuote;


		SBQQ__QuoteLine__c testQuoteLine = TestDataFactory.returnSingleQuoteLine(testQuote.Id, testProduct.Id);
		testQuoteLine.Stage__c = 'Identified';
		insert testQuoteLine;

		// Create a case list containing one test case
		List<Case> lstTestCases = TestDataFactory.returnCases(1, 'Sample_Request', testAccount, testContact, testUser);
		lstTestCases[0].QuoteLine__c = testQuoteLine.Id;
		lstTestCases[0].AssignedSampleStore__c = '';
		insert lstTestCases;

		// Create the input variable in the right format for assignSampleRequest
		AssignSampleRequest.AssignSampleRequestRequest testLstSampleRequest = new AssignSampleRequest.AssignSampleRequestRequest();
		testLstSampleRequest.lstCase = lstTestCases;
		List<AssignSampleRequest.AssignSampleRequestRequest> testRequests = new List<AssignSampleRequest.AssignSampleRequestRequest>();
		testRequests.add(testLstSampleRequest);

		AssignSampleRequest.assignSampleRequest(testRequests);

		//System.assertEquals(1, [SELECT Id FROM DebugLog__c].size() , 'An error should be logged due to Case.OwnerId being null' );
	} */
}