objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>This value will be set based on the IMCD Company of your User.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ImcdCompany__c.object
<CustomObject>
    <description>Custom Object used to store data specific to each IMCD company (see the IMCD global picklist). It is used (not only) for quote document generation purpose. It is related to user.</description>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <label>IMCD Company</label>
    <nameField>
        <label>IMCD Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMCD Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>BasePrice__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Base purchase price for this product as contracted with principal.</description>
        <label>Base Price</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Alert__c</fullName>
        <description>If empty the products are free to select</description>
        <label>Alert</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AllowedCountries__c</fullName>
        <description>Product allowed countries</description>
        <label>Allowed Countries</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ItemStatus__c</fullName>
        <description>Product item status</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>03.Active Pre Sales</fullName>
                    <label>Active Pre Sales</label>
                </value>
                <value>
                    <fullName>04.Active Sales</fullName>
                    <label>Active Sales</label>
                </value>
                <value>
                    <fullName>06.Inactive</fullName>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>01.New</fullName>
                    <label>New</label>
                </value>
                <value>
                    <fullName>07.Obsolete</fullName>
                    <label>Obsolete</label>
                </value>
                <value>
                    <fullName>05.Phase Out</fullName>
                    <label>Phase out</label>
                </value>
                <value>
                    <fullName>02.Temp Pre Sales</fullName>
                    <default>true</default>
                    <label>Temp Pre Sales</label>
                </value>
                <value>
                    <fullName>99.Rejected Temp</fullName>
                    <label>Rejected Temp</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <isActive>false</isActive>
                    <label>10</label>
                </value>
                <value>
                    <fullName>100</fullName>
                    <isActive>false</isActive>
                    <label>100</label>
                </value>
                <value>
                    <fullName>101</fullName>
                    <isActive>false</isActive>
                    <label>101</label>
                </value>
                <value>
                    <fullName>102</fullName>
                    <isActive>false</isActive>
                    <label>102</label>
                </value>
                <value>
                    <fullName>103</fullName>
                    <isActive>false</isActive>
                    <label>103</label>
                </value>
                <value>
                    <fullName>104</fullName>
                    <isActive>false</isActive>
                    <label>104</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <isActive>false</isActive>
                    <label>11</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <isActive>false</isActive>
                    <label>12</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <isActive>false</isActive>
                    <label>13</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <isActive>false</isActive>
                    <label>14</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <isActive>false</isActive>
                    <label>15</label>
                </value>
                <value>
                    <fullName>16</fullName>
                    <isActive>false</isActive>
                    <label>16</label>
                </value>
                <value>
                    <fullName>17</fullName>
                    <isActive>false</isActive>
                    <label>17</label>
                </value>
                <value>
                    <fullName>18</fullName>
                    <isActive>false</isActive>
                    <label>18</label>
                </value>
                <value>
                    <fullName>19</fullName>
                    <isActive>false</isActive>
                    <label>19</label>
                </value>
                <value>
                    <fullName>20</fullName>
                    <isActive>false</isActive>
                    <label>20</label>
                </value>
                <value>
                    <fullName>21</fullName>
                    <isActive>false</isActive>
                    <label>21</label>
                </value>
                <value>
                    <fullName>22</fullName>
                    <isActive>false</isActive>
                    <label>22</label>
                </value>
                <value>
                    <fullName>23</fullName>
                    <isActive>false</isActive>
                    <label>23</label>
                </value>
                <value>
                    <fullName>24</fullName>
                    <isActive>false</isActive>
                    <label>24</label>
                </value>
                <value>
                    <fullName>25</fullName>
                    <isActive>false</isActive>
                    <label>25</label>
                </value>
                <value>
                    <fullName>26</fullName>
                    <isActive>false</isActive>
                    <label>26</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Principal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pricipal of Product</description>
        <label>Principal</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You have to select a valid Global principal.</errorMessage>
            <filterItems>
                <field>Account.TF_RecordTypeDeveloperName__c</field>
                <operation>equals</operation>
                <value>Principal_Global</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <description>Standard product record type</description>
        <label>Product</label>
    </recordTypes>
    <recordTypes>
        <fullName>TempProduct</fullName>
        <active>true</active>
        <description>Record type for the creation of Temp Products</description>
        <label>Temp Product</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <description>Imcd Company for this user</description>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/testCPQadvancedSearchPlugin.cls
@istest
	public class testCPQadvancedSearchPlugin {

/*------------------------------------------------------------
		Author:        	Wim van Beek
		Company:       	NNCourage
		Description:   	Testclass for CPQadvancedSearchPlugin
		Inputs:        	https://community.steelbrick.com/t5/Developer-Guidebook/Product-Search-Plugin/ta-p/13626

		History
		May 18      Initial
------------------------------------------------------------*/	
	@testSetup 
	Public Static void setupData(){
		Account acc = (Account)CPQTestFactory.createSObject(new Account());
		insert acc;

		String IMCDref = Account.IMCDCompany__c.getDescribe().getPicklistValues()[0].getValue(); 
		PriceBook2 PB = (PriceBook2)CPQTestFactory.createSObject(new PriceBook2(Name='pb', ImcdCompany__c=IMCDref));
		insert PB;

		SBQQ__Quote__c quote = (SBQQ__Quote__c)CPQTestFactory.createSObject(new SBQQ__Quote__c());
		quote.SBQQ__PriceBookId__c = PB.id;
		quote.SBQQ__Account__c = acc.id;
		Insert quote;		

		Product2 Pr2 = (Product2)CPQTestFactory.createSObject(new Product2(Name='A Name45100', IsActive=true));
		Pr2.RecordType = IMCDUtils.getRecordType('Product2', 'TempProduct');
		insert Pr2;
		update Pr2;
		System.debug('------ Pr2 '+ Pr2);

		PricebookEntry PBE = (PricebookEntry)CPQTestFactory.createSObject(
							new PricebookEntry(IsActive = true, 
								UnitPrice=0,
								CurrencyIsoCode = 'EUR',
								Product2Id = Pr2.id, 
								Pricebook2Id=Test.getStandardPricebookId()));
		insert PBE;		
		
		System.debug('------ PBE '+ PBE);
		PBE = (PricebookEntry)CPQTestFactory.createSObject(
							new PricebookEntry(IsActive = true,
								UnitPrice=0, 
								BasePrice__c = true, 
								Product2Id = Pr2.id, 
								Pricebook2Id=quote.SBQQ__PriceBookId__c));
		insert PBE;	
}



	@istest (seealldata=false)
	Public Static void CPQadvancedMain(){
		Test.startTest();	
		Account acc = Database.Query(IMCDUtils.getCreatableFieldsSOQL('Account', 'id != null LIMIT 1'));
		PriceBook2 PB = Database.Query(IMCDUtils.getCreatableFieldsSOQL('PriceBook2', 'id != null LIMIT 1'));
		SBQQ__Quote__c quote = Database.Query(IMCDUtils.getCreatableFieldsSOQL('SBQQ__Quote__c', 'id != null LIMIT 1'));
		Product2 Pr2 = Database.Query(IMCDUtils.getCreatableFieldsSOQL('Product2', 'id != null LIMIT 1'));
		List<PricebookEntry> PBE = Database.Query(IMCDUtils.getCreatableFieldsSOQL('PricebookEntry', 'id != null '));
		Test.stopTest();

		CPQadvancedSearchPlugin plug = new CPQadvancedSearchPlugin();

		Map<String,Object> fieldValuesMap = new Map<String,Object>();
		fieldValuesMap.put('Principal__c',acc.Id);
		fieldValuesMap.put('Name','A');
		fieldValuesMap.put('ItemStatus__c','01.New');
		List<PricebookEntry> PBEres =  plug.search(quote, fieldValuesMap);
		System.debug('------ PBEres '+ PBEres);

		System.assertEquals(PBEres.size(), 1);
		System.assertEquals(PBEres[0].UnitPrice, 0);

		String billCountryCode = User.Countrycode.getDescribe().getPicklistValues()[1].getValue();
		acc.ShippingCountry =  billCountryCode ;
		update acc;
		Pr2.AllowedCountries__c = 'xx';
		update Pr2;
		PBEres =  plug.search(quote, fieldValuesMap);
		System.debug('------ PBEres '+ PBEres[0].Product2.Alert__c);
		System.assertEquals(PBEres[0].Product2.Alert__c, 'Invalid for country '+billCountryCode );

		acc.ShippingCountry =  null ;
		update acc;
		PBEres =  plug.search(quote, fieldValuesMap);
		System.debug('------ PBEres '+ PBEres[0].Product2.Alert__c);
		System.assertEquals(PBEres[0].Product2.Alert__c, 'Customer needs Sold To Country' );

		fieldValuesMap.clear();
		List<PricebookEntry> PBEres1 =  plug.search(quote, fieldValuesMap);
		System.assertEquals(PBEres1.size(), 0);
		
		// Rest of methods are not used but required by SBQQ.ProductSearchPlugin. Just to get covverage :(		
		plug.getAdditionalSearchFilters(quote, null);
		plug.isSearchCustom(quote, null);
		plug.isFilterHidden(quote, null);
		plug.getFilterDefaultValue(quote, null);
		plug.getAdditionalSearchFilters(quote, null);
		plug.isInputHidden(quote, null);
		plug.getInputDefaultValue(quote, null);
		plug.getAdditionalSuggestFilters(quote, null);
		plug.suggest(quote, null);
		plug.isSuggestCustom(quote, null);


	
	}
}