objects/AccountShiptoAddress__c.object
<CustomObject>
    <description>Custom object which has master/detail relationship with Account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Master/detail for Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship-to Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CountryLabel__c</fullName>
        <label>Country Label</label>
        <length>99</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FinalCountries</valueSetName>
        </valueSet>
    </fields>
    <label>Ship-to Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship-to Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestAccountShipToAddressTriggerHelper.cls
@isTest
public Class TestAccountShipToAddressTriggerHelper {

    @testSetup 
    static void setup() {
       TestDataFactory.createBypassCustomSetting();
       List<Account> testAccounts = TestDataFactory.createAccounts(1, Label.Customer_Sold_To_Account_Record_Type, TestDataFactoryUtils.getContextUserId(), '21100'); 
        
    }

    @isTest
    static void isCompanyLabelCopiedAcrossForInsert(){
        Account testAccount = [SELECT Id FROM Account][0];
        String expectedCountryCode = 'AU';
        String expectedCountryLabel = 'Australia';
        AccountShipToAddress__c testAddress = new AccountShipToAddress__c(Account__c = testAccount.Id,
                                                                Country__c = expectedCountryCode);
        Test.startTest();
        
            insert testAddress;
        
        Test.stopTest();
        System.assertEquals(expectedCountryLabel, [SELECT CountryLabel__c FROM AccountShipToAddress__c WHERE ID =: testAddress.Id][0].CountryLabel__c);
    }

    @isTest
    static void isCompanyLabelCopiedAcrossForUpdate(){
        Account testAccount = [SELECT Id FROM Account][0];
        String expectedCountryCode = 'AU';
        String expectedCountryLabel = 'Albania';
        AccountShipToAddress__c testAddress = new AccountShipToAddress__c(Account__c = testAccount.Id,
                                                                Country__c = expectedCountryCode);
        insert testAddress;
        Test.startTest();

            testAddress.Country__c = 'AL';
            update testAddress;
        
        Test.stopTest();
        System.assertEquals(expectedCountryLabel, [SELECT CountryLabel__c FROM AccountShipToAddress__c WHERE ID =: testAddress.Id][0].CountryLabel__c);
    }
}