objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>This value will be set based on the IMCD Company of your User.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ImcdCompany__c.object
<CustomObject>
    <description>Custom Object used to store data specific to each IMCD company (see the IMCD global picklist). It is used (not only) for quote document generation purpose. It is related to user.</description>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <label>IMCD Company</label>
    <nameField>
        <label>IMCD Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMCD Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LOB1__c</fullName>
        <inlineHelpText>Leaving this field empty, will automatically copy the Primary LOB1/2/3 values from the Account</inlineHelpText>
        <label>LOB1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SharingAccess__c.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOB1__c</fullName>
        <label>LOB1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <label>Sharing Access</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sharing Access</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/LOB1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advanced Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Coatings &amp; Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Food</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care and I&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Lubricants</fullName>
    </customValue>
    <customValue>
        <fullName>Other Specialties</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Care</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmaceuticals</fullName>
    </customValue>
    <customValue>
        <fullName>Synthesis</fullName>
    </customValue>
    <masterLabel>LOB1</masterLabel>
</GlobalValueSet>

classes/QueueableOppRecalculateSharing.cls
/******************************************************************************************************************************************************************
* Author: Eli Pogorelov
* Company: Salesforce
* Description: Queueable for recalculation of Sharing based on Opportunities records
* Inputs : Map<String, Map <String, List<SharingAccess__c> > >, Map<String, Map <String, List<SharingAccess__c> > >, Map<String, List<SharingAccess__c> >,
* Map<String, List<SharingAccess__c> >,  Map<Id,Set<Id>>, List<AccountShare>
* Test Class :  TestSharingAccessTriggerHelper
* History :
******************************************************************************************************************************************************************/
public without sharing class QueueableOppRecalculateSharing implements Queueable
{
    Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessMap = new Map<String, Map <String, List<SharingAccess__c> > >();
    Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessPrincipalMap = new Map<String, Map <String, List<SharingAccess__c> > >();
    Map<String, List<SharingAccess__c> > globalSharingAccessesMap = new Map<String, List<SharingAccess__c> >();
    Map<String, List<SharingAccess__c> > globalSharingAccessesPrincipalMap = new Map<String, List<SharingAccess__c> >();
    Map<Id,Set<Id>> ownersToAccIds = new Map<Id,Set<Id>>();

    List<AccountShare> accSharepassedToQueueble = new List<AccountShare>();


    public QueueableOppRecalculateSharing(Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessMap, Map<String, List<SharingAccess__c> > globalSharingAccessesNoPrincipalMap, Map<Id,Set<Id>> ownersToAccIds,
                                        Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessPrincipalMap,Map<String, List<SharingAccess__c> > globalSharingAccessesPrincipalMap, List<AccountShare> accSharepassedToQueueble)
    {
        this.lob1toSharingAccessMap = lob1toSharingAccessMap;
        this.globalSharingAccessesMap = globalSharingAccessesNoPrincipalMap;
        this.ownersToAccIds = ownersToAccIds;
        this.lob1toSharingAccessPrincipalMap = lob1toSharingAccessPrincipalMap;
        this.globalSharingAccessesPrincipalMap = globalSharingAccessesPrincipalMap;
        this.accSharepassedToQueueble = accSharepassedToQueueble;
    }

    public void execute(QueueableContext context)
    {
        try
        {
            List<OpportunityShare> oppSharepassedToQueueble = new List<OpportunityShare>();
            if(!lob1toSharingAccessMap.isEmpty())
            {

                List<AccountShare> accShareToInsert = new List<AccountShare>();
                List<OpportunityShare> oppShareToInsert = new List<OpportunityShare>();
                Set<String> imcdCompNames = new Set<String>();

                for(Map <String, List<SharingAccess__c> >  value : lob1toSharingAccessMap.values() )
                {
                    imcdCompNames.addAll(value.keySet());
                }

                for(Opportunity op : [SELECT Id, AccountId, Account.IMCDCompany__c, Account.ParentId, LOB1__c
                                      FROM Opportunity
                                      WHERE LOB1__c IN : lob1toSharingAccessMap.keySet() AND Account.IMCDCompany__c IN :  imcdCompNames])
                {//sharing Account if LOB1 & IMCDCompany match
                    if(lob1toSharingAccessMap.get(op.LOB1__c)!=null && lob1toSharingAccessMap.get(op.LOB1__c).get(op.Account.IMCDCompany__c)!=null)
                    {
                        //sharing the Opportunity
                        oppShareToInsert.addAll(SharingUtils.opportunitySharing(op.Id,lob1toSharingAccessMap.get(op.LOB1__c).get(op.Account.IMCDCompany__c), Label.READ_WRITE_ACCESS, Label.MANUAL_RAW_CAUSE));
                        //SharingUtils.debugSharingReason('Opportunity','LOB1 & IMCDCompany match','QueueableOppRecalculateSharing',lob1toSharingAccessMap.get(op.LOB1__c).get(op.Account.IMCDCompany__c));
                        //sharing the sold to Account and Regional Account
                        if(op.Account.ParentId!=null)
                        {
                            accShareToInsert.addAll(SharingUtils.accountSharing(op.AccountId, op.Account.ParentId, lob1toSharingAccessMap.get(op.LOB1__c).get(op.Account.IMCDCompany__c), Label.READ_WRITE_ACCESS, Label.NO_ACCESS, Label.MANUAL_RAW_CAUSE, ownersToAccIds));
                            //SharingUtils.debugSharingReason('Account','sharing the soldTo+C2 LOB1 & IMCDCompany match','QueueableOppRecalculateSharing',lob1toSharingAccessMap.get(op.LOB1__c).get(op.Account.IMCDCompany__c));
                        }
                        else
                        {
                            accShareToInsert.addAll(SharingUtils.accountSharing(op.AccountId, null, lob1toSharingAccessMap.get(op.LOB1__c).get(op.Account.IMCDCompany__c), Label.READ_WRITE_ACCESS, Label.NO_ACCESS, Label.MANUAL_RAW_CAUSE, ownersToAccIds));
                            //SharingUtils.debugSharingReason('Account','sharing the soldTo LOB1 & IMCDCompany match','QueueableOppRecalculateSharing',lob1toSharingAccessMap.get(op.LOB1__c).get(op.Account.IMCDCompany__c));
                        }
                    }
                }
                if (!accShareToInsert.isEmpty() && !oppShareToInsert.isEmpty())
                {/*if we are going to hit DML limit we'll insert what possible and pass the remains of the sharing records
                    next queueable to get fresh set of limits*/
                    SharingUtils.combineRemainAndSharingList(accShareToInsert,accSharepassedToQueueble);
                    SharingUtils.checkForDMLlimitAndInsertOrDeleteSharing(accShareToInsert,accSharepassedToQueueble,oppShareToInsert,oppSharepassedToQueueble,true);
                }// if we only have remains of AccountShare from other queueable and we can insert them all in current transaction
                else
                {
                    if(accSharepassedToQueueble.size() > 0)
                    {
                        SharingUtils.checkForDMLlimitAndInsertOrDeleteSharingRemains(accSharepassedToQueueble, true);
                    }
                }
            }
            system.debug('+++QueueableOppRecalculateSharing getHeapSize()'+ Limits.getHeapSize());
            //Sharing Accounts and Quotes based on Quotes
            if(!Test.isRunningTest())
            {
                QueueableQuoteRecalculateSharing insertAccAndQuoteSharesBasedQtJob = new QueueableQuoteRecalculateSharing(lob1toSharingAccessMap, globalSharingAccessesMap, ownersToAccIds,
                lob1toSharingAccessPrincipalMap, globalSharingAccessesPrincipalMap, accSharepassedToQueueble, oppSharepassedToQueueble) ;
                System.enqueueJob(insertAccAndQuoteSharesBasedQtJob);
            }
        }
        catch(Exception ex)
        {
            DebugLog.addException(ex, 'QueueableOppRecalculateSharing') ;
        }
    }

}