objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>This value will be set based on the IMCD Company of your User.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Global_Bypass_Processes_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global Bypass Control Panel</description>
    <label>Global Bypass Processes Settings</label>
</CustomObject>

objects/ImcdCompany__c.object
<CustomObject>
    <description>Custom Object used to store data specific to each IMCD company (see the IMCD global picklist). It is used (not only) for quote document generation purpose. It is related to user.</description>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <label>IMCD Company</label>
    <nameField>
        <label>IMCD Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMCD Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LOB1__c</fullName>
        <inlineHelpText>Leaving this field empty, will automatically copy the Primary LOB1/2/3 values from the Account</inlineHelpText>
        <label>LOB1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <businessProcess>Standard Opportunity</businessProcess>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>FullSegmentsNumber__c</fullName>
        <description>Product full segments number</description>
        <externalId>true</externalId>
        <label>Full Segments Number</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <description>Standard product record type</description>
        <label>Product</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
</CustomObject>

objects/SharingAccess__c.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOB1__c</fullName>
        <label>LOB1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrincipalId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Principal</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a Principal Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Principal Global</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>SharingAcees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sharing Access</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sharing Access</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <description>Imcd Company for this user</description>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/LOB1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advanced Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Coatings &amp; Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Food</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care and I&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Lubricants</fullName>
    </customValue>
    <customValue>
        <fullName>Other Specialties</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Care</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmaceuticals</fullName>
    </customValue>
    <customValue>
        <fullName>Synthesis</fullName>
    </customValue>
    <masterLabel>LOB1</masterLabel>
</GlobalValueSet>

classes/TestOpportunityLineItemTriggerHelper.cls
/******************************************************************************************************************************************************************
 * Author: Aviad Efergan, Eli Pogorelov
 * Company: Salesforce
 * Description: Tests for OpportunityLineItemTriggerHelper
 * History :
 ******************************************************************************************************************************************************************/
@isTest
	private class TestOpportunityLineItemTriggerHelper {

	@testSetup
	static void createTestData() {
		Global_Bypass_Processes_Settings__c cs = TestDataFactory.createBypassCustomSetting();
		TestDataFactory.createRecordTypeIds();
		TestDataFactory.createIntegrationSettings();

		list<Account> soldToAccounts = TestDataFactory.createAccounts(1, Label.Customer_Sold_To_Account_Record_Type, TestDataFactoryUtils.getContextUserId(), '79100');
		soldToAccounts.addAll(TestDataFactory.createAccounts(1, Label.Customer_Sold_To_Account_Record_Type, TestDataFactoryUtils.getContextUserId(), '13100'));

		soldToAccounts.addAll(TestDataFactory.createAccounts(1, Label.Customer_Sold_To_Account_Record_Type, TestDataFactoryUtils.getContextUserId(), '91100'));
		List<Account> regionAccounts = TestDataFactory.createAccounts(3, Label.Global_Principa_Account_RecordType, TestDataFactoryUtils.getContextUserId(), '13100');

		for (Integer i = 0; i < soldToAccounts.size(); i++) {
			soldToAccounts[i].ParentId = regionAccounts[i].Id;
		}

		update soldToAccounts;

		/*Creating Test Standard, and Custom Pricebook, pricebookEntry*/
		List<Pricebook2> defpricebooks = TestDataFactory.createDefaultPricebooks();

		Pricebook2 standardPricebook = new Pricebook2(
				Id = Test.getStandardPricebookId(),
				IsActive = true,
				ImcdCompany__c = '22100'
		);
		update standardPricebook;

		List<String> imcdCompaniesForTest = new List<String>{'79100','13100','91100'};
		TestDataFactory.createImcdCompanies(imcdCompaniesForTest);

		list<Opportunity> oppLst = TestDataFactory.returnOpportunities(1, soldToAccounts[0], new List<String>{'Coatings & Construction'});
		oppLst.addAll(TestDataFactory.returnOpportunities(1, soldToAccounts[1], new List<String>{'Coatings & Construction'}));
		oppLst.addAll(TestDataFactory.returnOpportunities(1, soldToAccounts[1], new List<String>{'Food'}));
		oppLst.addAll(TestDataFactory.returnOpportunities(1, soldToAccounts[2], new List<String>{'Lubricants'}));
		oppLst[0].SBQQ__QuotePricebookId__c = defpricebooks[1].Id;
		oppLst[1].SBQQ__QuotePricebookId__c = defpricebooks[1].Id;
		insert oppLst;

		list<User> usersLst = TestDataFactory.createUsers(1, Label.Standard_User_Profile_Name, '79100');

		list<SharingAccess__c> shareAccsLst = TestDataFactory.getSharingAccessList(usersLst, '79100', 'Coatings & Construction', false);
		shareAccsLst[0].PrincipalId__c = regionAccounts[0].Id;
		shareAccsLst.addAll(TestDataFactory.getSharingAccessList(usersLst, '79100', 'Food', true));
		shareAccsLst[1].PrincipalId__c = regionAccounts[0].Id;
		shareAccsLst.addAll(TestDataFactory.getSharingAccessList(usersLst, '79100', 'Lubricants', false));
		shareAccsLst[2].PrincipalId__c = regionAccounts[0].Id;
		shareAccsLst.addAll(TestDataFactory.getSharingAccessList(usersLst, '79100', '', true));
		shareAccsLst[3].PrincipalId__c = regionAccounts[0].Id;
		shareAccsLst.addAll(TestDataFactory.getSharingAccessList(usersLst, '79100', '', false));
		shareAccsLst[4].PrincipalId__c = regionAccounts[0].Id;
		insert shareAccsLst;

		/*Creatting product to relate to Opp/Quote LineItems*/
		Product2 prod = TestDataFactory.createProduct(regionAccounts[0].Id, 'kjdfsfgfhs898');

		/*Creating pbentry to relate to Opp LineItems*/
		Pricebook2 standardPB = [SELECT Id FROM Pricebook2 WHERE isStandard = true];
		PricebookEntry standardPBE = TestDataFactory.createPricebookEntry(standardPB.Id, prod.Id, 'USD');
		//PricebookEntry standardPBE = TestDataFactory.createPricebookEntry(standardPB.Id, prod.Id);
		PricebookEntry pbentry = TestDataFactory.createPricebookEntry(defpricebooks[1].Id, prod.Id);
	}

	@isTest
	static void test_accountShareBasedOppLineItem_match() {
		Test.startTest();
		//Below test data is created to relate opportunity product with quotelineitem
		Product2 prod = [Select Id from Product2 WHERE FullSegmentsNumber__c = 'kjdfsfgfhs898' limit 1];
		PriceBookEntry pbEntry= [Select Id,UnitPrice from PriceBookEntry where Product2Id=: prod.Id AND Pricebook2Id !=: Test.getStandardPriceBookId() limit 1];

		list<Opportunity> oppLst = [Select Id, CurrencyIsoCode, AccountId, Account.ParentId From Opportunity Where Account.ImcdCompany__c = '79100' And LOB1__c = 'Coatings & Construction'];

		List<Account> testSoldToAccounts = TestDataFactory.returnAccounts(1, Label.Customer_Sold_To_Account_Record_Type, TestDataFactoryUtils.getContextUserId(), '79100');
		insert testSoldToAccounts;

		list<Sbqq__Quote__c> quoteList = TestDataFactory.returnQuotes(1, testSoldToAccounts[0], new List<String>{'Food'});
		quoteList[0].SBQQ__Opportunity2__c = oppLst[0].Id;
		insert quoteList;
		/*Creating Opp/Quote Line Items for Principal match scenario*/

		list<SBQQ__QuoteLine__c> qtLineLst = TestDataFactory.returnQuoteLine(1, quoteList[0].Id, prod.Id);
		insert qtLineLst ;

		list<OpportunityLineItem> oppLineItemList = TestDataFactory.returnOpportunityLineItem(1, oppLst[0].Id, pbEntry);
		oppLineItemList[0].SBQQ__QuoteLine__c = qtLineLst[0].Id;

		Test.stopTest();

		insert oppLineItemList;

		Id sharedUserId = [Select Id From User Where Profile.Name =: Label.Standard_User_Profile_Name and ImcdCompany__c = '79100' limit 1].Id;
		//Assert correct share match by LOB, Company and Principal to Opportunity
		//System.assert([Select UserOrGroupId From OpportunityShare Where OpportunityId =: oppLst[0].Id and UserOrGroupId =: sharedUserId].size() > 0);
		//Assert match soldTo and regional account
		//System.assert([Select UserOrGroupId From AccountShare Where AccountId =: oppLst[0].AccountId and UserOrGroupId =: sharedUserId].size() > 0);
		//System.assert([Select UserOrGroupId From AccountShare Where AccountId =: oppLst[0].Account.ParentId and UserOrGroupId =: sharedUserId].size() > 0);
	}

	@isTest
	static void test_accountShareBasedOppLineItem_match_global() {
		Test.startTest();
		Product2 prod = [Select Id from Product2 WHERE FullSegmentsNumber__c = 'kjdfsfgfhs898' limit 1];

		PriceBookEntry pbEntry= [Select Id,UnitPrice from PriceBookEntry where Product2Id=: prod.Id AND Pricebook2Id !=: Test.getStandardPriceBookId() limit 1];

		list<Opportunity> oppLst = [Select Id, CurrencyIsoCode, AccountId, Account.ParentId From Opportunity Where Account.ImcdCompany__c = '13100' And LOB1__c = 'Food'];

		List<Account> testSoldToAccounts = TestDataFactory.returnAccounts(1, Label.Customer_Sold_To_Account_Record_Type, TestDataFactoryUtils.getContextUserId(), '79100');
		insert testSoldToAccounts;

		list<Sbqq__Quote__c> quoteList = TestDataFactory.returnQuotes(1, testSoldToAccounts[0], new List<String>{'Food'});
		quoteList[0].SBQQ__Opportunity2__c = oppLst[0].Id;
		insert quoteList;
		/*Creating Opp/Quote Line Items for Principal match scenario*/

		list<SBQQ__QuoteLine__c> qtLineLst = TestDataFactory.returnQuoteLine(1, quoteList[0].Id, prod.Id);
		insert qtLineLst ;

		list<OpportunityLineItem> oppLineItemList = TestDataFactory.returnOpportunityLineItem(1, oppLst[0].Id, pbEntry);
		oppLineItemList[0].SBQQ__QuoteLine__c = qtLineLst[0].Id;

		Test.stopTest();

		insert oppLineItemList;

		Id sharedUserId = [Select Id From User Where Profile.Name =: Label.Standard_User_Profile_Name and ImcdCompany__c = '79100' limit 1].Id;
		//Assert correct share match by LOB, Company and Principal to Opportunity
		//System.assert([Select UserOrGroupId From OpportunityShare Where OpportunityId =: oppLst[0].Id and UserOrGroupId =: sharedUserId].size() > 0);
		//Assert match soldTo and regional account
		//System.assert([Select UserOrGroupId From AccountShare Where AccountId =: oppLst[0].AccountId and UserOrGroupId =: sharedUserId].size() > 0);
		//System.assert([Select UserOrGroupId From AccountShare Where AccountId =: oppLst[0].Account.ParentId and UserOrGroupId =: sharedUserId].size() > 0);
	}

	@isTest
	static void test_accountShareBasedOppLineItem_no_match() {
		Test.startTest();
		Product2 prod = [Select Id from Product2 WHERE FullSegmentsNumber__c = 'kjdfsfgfhs898' limit 1];

		PriceBookEntry pbEntry= [Select Id,UnitPrice from PriceBookEntry where Product2Id=: prod.Id AND Pricebook2Id !=: Test.getStandardPriceBookId() limit 1];

		list<Opportunity> oppLst = [Select Id, CurrencyIsoCode, AccountId, Account.ParentId From Opportunity Where Account.ImcdCompany__c = '91100' And LOB1__c = 'Lubricants'];

		List<Account> testSoldToAccounts = TestDataFactory.returnAccounts(1, Label.Customer_Sold_To_Account_Record_Type, TestDataFactoryUtils.getContextUserId(), '79100');
		insert testSoldToAccounts;

		list<Sbqq__Quote__c> quoteList = TestDataFactory.returnQuotes(1, testSoldToAccounts[0], new List<String>{'Food'});
		quoteList[0].SBQQ__Opportunity2__c = oppLst[0].Id;
		insert quoteList;
		/*Creating Opp/Quote Line Items for Principal match scenario*/

		list<SBQQ__QuoteLine__c> qtLineLst = TestDataFactory.returnQuoteLine(1, quoteList[0].Id, prod.Id);
		insert qtLineLst ;

		list<OpportunityLineItem> oppLineItemList = TestDataFactory.returnOpportunityLineItem(1, oppLst[0].Id, pbEntry);
		oppLineItemList[0].SBQQ__QuoteLine__c = qtLineLst[0].Id;
		Test.stopTest();

		insert oppLineItemList;

		Id sharedUserId = [Select Id From User Where Profile.Name =: Label.Standard_User_Profile_Name and ImcdCompany__c = '79100' limit 1].Id;
		//Assert no share match by LOB, Company and Principal to Opportunity
		//System.assert([Select UserOrGroupId From OpportunityShare Where OpportunityId =: oppLst[0].Id and UserOrGroupId =: sharedUserId].size() == 0);
		//Assert no match soldTo and regional account
		//System.assert([Select UserOrGroupId From AccountShare Where AccountId =: oppLst[0].AccountId and UserOrGroupId =: sharedUserId].size() == 0);
		//System.assert([Select UserOrGroupId From AccountShare Where AccountId =: oppLst[0].Account.ParentId and UserOrGroupId =: sharedUserId].size() == 0);
	}
}