objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>This value will be set based on the IMCD Company of your User.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AccountLob__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LOB Classifications</relationshipLabel>
        <relationshipName>LOB_Classifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LOB1__c</fullName>
        <label>LOB1</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <label>LOB Classification</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>LOB Classification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LOB Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ImcdCompany__c.object
<CustomObject>
    <description>Custom Object used to store data specific to each IMCD company (see the IMCD global picklist). It is used (not only) for quote document generation purpose. It is related to user.</description>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <label>IMCD Company</label>
    <nameField>
        <label>IMCD Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMCD Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SharingAccess__c.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOB1__c</fullName>
        <label>LOB1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <label>Sharing Access</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sharing Access</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/LOB1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advanced Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Coatings &amp; Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Food</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care and I&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Lubricants</fullName>
    </customValue>
    <customValue>
        <fullName>Other Specialties</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Care</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmaceuticals</fullName>
    </customValue>
    <customValue>
        <fullName>Synthesis</fullName>
    </customValue>
    <masterLabel>LOB1</masterLabel>
</GlobalValueSet>

classes/QueueableAccLobRecalculateSharing.cls
/******************************************************************************************************************************************************************
* Author: Eli Pogorelov
* Company: Salesforce
* Description: Queueable for recalculation of Sharing based on AccountLob records
* Inputs : Map<String, Map <String, List<SharingAccess__c> > >, Map<String, Map <String, List<SharingAccess__c> > >, Map<String, List<SharingAccess__c> >,
* Map<String, List<SharingAccess__c> >, Map<Id,Set<Id>>
* Test Class :  TestSharingAccessTriggerHelper
* History :
******************************************************************************************************************************************************************/
public without sharing class QueueableAccLobRecalculateSharing implements Queueable
{
    Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessMap = new Map<String, Map <String, List<SharingAccess__c> > >();
    Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessPrincipalMap = new Map<String, Map <String, List<SharingAccess__c> > >();
    Map<String, List<SharingAccess__c> > globalSharingAccessesMap = new Map<String, List<SharingAccess__c> >();
    Map<String, List<SharingAccess__c> > globalSharingAccessesPrincipalMap = new Map<String, List<SharingAccess__c> >();
    Map<Id,Set<Id>> ownersToAccIds = new Map<Id,Set<Id>>();

    public QueueableAccLobRecalculateSharing( Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessMap, Map<String, List<SharingAccess__c> > globalSharingAccessesNoPrincipalMap, Map<Id,Set<Id>> ownersToAccIds,
                                            Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessPrincipalMap, Map<String, List<SharingAccess__c> > globalSharingAccessesPrincipalMap)
    {
        this.lob1toSharingAccessMap = lob1toSharingAccessMap;
        this.globalSharingAccessesMap = globalSharingAccessesNoPrincipalMap;
        this.lob1toSharingAccessPrincipalMap = lob1toSharingAccessPrincipalMap;
        this.globalSharingAccessesPrincipalMap = globalSharingAccessesPrincipalMap;
        this.ownersToAccIds = ownersToAccIds;
    }

    public void execute(QueueableContext context)
    {
        try
        {
            List<AccountShare> accSharepassedToQueueble = new List<AccountShare>();
            if(!lob1toSharingAccessMap.isEmpty())
            {
                List<AccountLob__c> accLobList = new List<AccountLob__c>();
                List<AccountShare> accShareToInsert = new List<AccountShare>();
                Set<String> imcdCompNames = new Set<String>();

                for(Map <String, List<SharingAccess__c> >  value : lob1toSharingAccessMap.values() )
                {
                    imcdCompNames.addAll(value.keySet());
                }

                for(AccountLob__c al : [SELECT Id, Account__c, Account__r.IMCDCompany__c, Account__r.ParentId, LOB1__c
                                        FROM AccountLob__c
                                        WHERE LOB1__c IN : lob1toSharingAccessMap.keySet() AND Account__r.IMCDCompany__c IN : imcdCompNames])
                {
                    //sharing Account if LOB1 & IMCDCompany match
                    if(lob1toSharingAccessMap.get(al.LOB1__c)!=null && lob1toSharingAccessMap.get(al.LOB1__c).get(al.Account__r.IMCDCompany__c)!=null)
                    {//sharing the sold to Account and Regional Account
                        if(al.Account__r.ParentId!=null)
                        {
                            accShareToInsert.addAll(SharingUtils.accountSharing(al.Account__c, al.Account__r.ParentId, lob1toSharingAccessMap.get(al.LOB1__c).get(al.Account__r.IMCDCompany__c), Label.READ_WRITE_ACCESS, Label.NO_ACCESS, Label.MANUAL_RAW_CAUSE, ownersToAccIds ));
                            SharingUtils.debugSharingReason('Account','delete the soldTo LOB1 & IMCDCompany match','QueueableAccLobDeleteSharing',lob1toSharingAccessMap.get(al.LOB1__c).get(al.Account__r.IMCDCompany__c));
                        }
                        else
                        {
                            accShareToInsert.addAll(SharingUtils.accountSharing(al.Account__c, null, lob1toSharingAccessMap.get(al.LOB1__c).get(al.Account__r.IMCDCompany__c), Label.READ_WRITE_ACCESS, Label.NO_ACCESS, Label.MANUAL_RAW_CAUSE, ownersToAccIds ));
                            SharingUtils.debugSharingReason('Account','sharing the C2 LOB1 & IMCDCompany match','QueueableAccLobRecalculateSharing',lob1toSharingAccessMap.get(al.LOB1__c).get(al.Account__r.IMCDCompany__c));
                        }
                    }
                }
                if(!accShareToInsert.isEmpty())
                {/*if we are going to hit DML limit we'll insert what possible and pass the remains of the sharing records
                    next queueable to get fresh set of limits*/
                    SharingUtils.checkForDMLlimitAndInsertOrDeleteSharing(accShareToInsert,accSharepassedToQueueble, true);
                }

            }
            //Sharing Accounts and Opps based on Opportunities
            QueueableOppRecalculateSharing insertAccAndOppSharesBasedOppJob = new QueueableOppRecalculateSharing(lob1toSharingAccessMap, globalSharingAccessesMap, ownersToAccIds, lob1toSharingAccessPrincipalMap, globalSharingAccessesPrincipalMap, accSharepassedToQueueble);
            if(!Test.isRunningTest() )
            {
                System.enqueueJob(insertAccAndOppSharesBasedOppJob);
            }
        }
        catch(Exception ex)
        {
            DebugLog.addException(ex, 'QueueableAccLobRecalculateSharing') ;
        }
    }

}