objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>This value will be set based on the IMCD Company of your User.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DebugLog__c.object
<CustomObject>
    <label>Debug Log (IMCD)</label>
    <nameField>
        <displayFormat>Log # {0000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ImcdCompany__c.object
<CustomObject>
    <description>Custom Object used to store data specific to each IMCD company (see the IMCD global picklist). It is used (not only) for quote document generation purpose. It is related to user.</description>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <label>IMCD Company</label>
    <nameField>
        <label>IMCD Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMCD Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ItemStatus__c</fullName>
        <description>Product item status</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>03.Active Pre Sales</fullName>
                    <label>Active Pre Sales</label>
                </value>
                <value>
                    <fullName>04.Active Sales</fullName>
                    <label>Active Sales</label>
                </value>
                <value>
                    <fullName>06.Inactive</fullName>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>01.New</fullName>
                    <label>New</label>
                </value>
                <value>
                    <fullName>07.Obsolete</fullName>
                    <label>Obsolete</label>
                </value>
                <value>
                    <fullName>05.Phase Out</fullName>
                    <label>Phase out</label>
                </value>
                <value>
                    <fullName>02.Temp Pre Sales</fullName>
                    <default>true</default>
                    <label>Temp Pre Sales</label>
                </value>
                <value>
                    <fullName>99.Rejected Temp</fullName>
                    <label>Rejected Temp</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <isActive>false</isActive>
                    <label>10</label>
                </value>
                <value>
                    <fullName>100</fullName>
                    <isActive>false</isActive>
                    <label>100</label>
                </value>
                <value>
                    <fullName>101</fullName>
                    <isActive>false</isActive>
                    <label>101</label>
                </value>
                <value>
                    <fullName>102</fullName>
                    <isActive>false</isActive>
                    <label>102</label>
                </value>
                <value>
                    <fullName>103</fullName>
                    <isActive>false</isActive>
                    <label>103</label>
                </value>
                <value>
                    <fullName>104</fullName>
                    <isActive>false</isActive>
                    <label>104</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <isActive>false</isActive>
                    <label>11</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <isActive>false</isActive>
                    <label>12</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <isActive>false</isActive>
                    <label>13</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <isActive>false</isActive>
                    <label>14</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <isActive>false</isActive>
                    <label>15</label>
                </value>
                <value>
                    <fullName>16</fullName>
                    <isActive>false</isActive>
                    <label>16</label>
                </value>
                <value>
                    <fullName>17</fullName>
                    <isActive>false</isActive>
                    <label>17</label>
                </value>
                <value>
                    <fullName>18</fullName>
                    <isActive>false</isActive>
                    <label>18</label>
                </value>
                <value>
                    <fullName>19</fullName>
                    <isActive>false</isActive>
                    <label>19</label>
                </value>
                <value>
                    <fullName>20</fullName>
                    <isActive>false</isActive>
                    <label>20</label>
                </value>
                <value>
                    <fullName>21</fullName>
                    <isActive>false</isActive>
                    <label>21</label>
                </value>
                <value>
                    <fullName>22</fullName>
                    <isActive>false</isActive>
                    <label>22</label>
                </value>
                <value>
                    <fullName>23</fullName>
                    <isActive>false</isActive>
                    <label>23</label>
                </value>
                <value>
                    <fullName>24</fullName>
                    <isActive>false</isActive>
                    <label>24</label>
                </value>
                <value>
                    <fullName>25</fullName>
                    <isActive>false</isActive>
                    <label>25</label>
                </value>
                <value>
                    <fullName>26</fullName>
                    <isActive>false</isActive>
                    <label>26</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <description>Standard product record type</description>
        <label>Product</label>
    </recordTypes>
    <recordTypes>
        <fullName>TempProduct</fullName>
        <active>true</active>
        <description>Record type for the creation of Temp Products</description>
        <label>Temp Product</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <description>Imcd Company for this user</description>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestTempProductPrice.cls
/*------------------------------------------------------------	
Author:        Jeroen Burgers	
Company:       Salesforce	
User Story:	   https://imcdgroup.atlassian.net/browse/SFDP-109
History	
	06/06/2018	   Created test class, 100% test coverage.
------------------------------------------------------------*/	
@isTest
private class TestTempProductPrice {

	@testsetup
    public static void testsetup() {
		// disable process builders and triggers
        TestDataFactoryUtils.runTriggers(false);
        TestDataFactoryUtils.runProcessBuilders(false);
        List<User> lstUsers = TestDataFactory.createUsers(1, Label.Standard_User_Profile_Name, '21100');
        List<Account> lstPrincipal = TestDataFactory.createAccounts(1, Label.Global_Principa_Account_Recordtype, lstUsers[0].Id, '21100');
		List<Product2> lstProduct = TestDataFactory.createProducts(2, lstPrincipal[0].Id, '02.Temp Pre Sales', 'TempProduct');
        TestDataFactory.createPricebookEntry(Test.getStandardPricebookId(), lstProduct[0].Id);
		TestDataFactory.createPricebookEntry(Test.getStandardPricebookId(), lstProduct[1].Id);
        TestDataFactory.createDefaultPricebooks();
	}
    
	@isTest
    static void testDataSetup () {
        System.assertEquals(1, [SELECT ImcdCompany__c FROM Pricebook2 WHERE ImcdCompany__c = '21100'].size(), 'TestSetup issue, Pricebooks did not get created');
        System.assertEquals(2, [SELECT Id FROM Product2 WHERE ItemStatus__c='02.Temp Pre Sales'].size(), 'TestSetup issue, Temp product did not get created');
    }
    
	@isTest
	static void testCreateProductPriceSingle () {
		List <TempProductPrice.TempProductPriceRequest> lstRequest = new List <TempProductPrice.TempProductPriceRequest>();
 		TempProductPrice.TempProductPriceRequest request = new TempProductPrice.TempProductPriceRequest();
		List<Product2> lstProduct = [SELECT Id FROM Product2];
        request.productId = lstProduct[0].Id;
        request.imcdCompany = '21100';
		lstRequest.add(request);
        TempProductPrice.CreateTempProductPrice(lstRequest);

        System.assertEquals(1, [SELECT Id FROM PricebookEntry WHERE Pricebook2.ImcdCompany__c = '21100'].size(), 'A single PriceBookEntry record should have been created');
    }
    
	@isTest
	static void testCreateProductDmlException () {
		List <TempProductPrice.TempProductPriceRequest> lstRequest = new List <TempProductPrice.TempProductPriceRequest>();
 		TempProductPrice.TempProductPriceRequest request = new TempProductPrice.TempProductPriceRequest();
		List<Product2> lstProduct = [SELECT Id FROM Product2];
        request.productId = lstProduct[0].Id;
        request.imcdCompany = '21100';
		lstRequest.add(request);
        // remove products to cause exception
        delete [SELECT Id FROM Product2 WHERE Id =: lstProduct[0].Id];
        TempProductPrice.CreateTempProductPrice(lstRequest);

        System.assertEquals(1, [SELECT Id FROM DebugLog__c].size(), 'Test should fail, exception not logged in DebugLog__c');
    }
    
    @isTest
	static void testCreateProductPriceMulti () {
		List <TempProductPrice.TempProductPriceRequest> lstRequest = new List <TempProductPrice.TempProductPriceRequest>();
        TempProductPrice.TempProductPriceRequest request1 = new TempProductPrice.TempProductPriceRequest();
		TempProductPrice.TempProductPriceRequest request2 = new TempProductPrice.TempProductPriceRequest();
		List<Product2> lstProduct = [SELECT Id FROM Product2];     
		request1.productId = lstProduct[0].Id;
        request1.imcdCompany = '21100';
		lstRequest.add(request1);
        request2.productId = lstProduct[1].Id;
        request2.imcdCompany = '21100';
		lstRequest.add(request2);
        TempProductPrice.CreateTempProductPrice(lstRequest);
		System.assertEquals(2, [SELECT Id FROM PricebookEntry WHERE Pricebook2.ImcdCompany__c = '21100'].size(), 'Two PriceBookEntry records should have been created');
    }
}