objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>This value will be set based on the IMCD Company of your User.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntegrationId__c</fullName>
        <externalId>true</externalId>
        <label>IntegrationId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LockedForIntegration__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating when a Prospect has been sent for Integration. When Checkbox is set, Validation rules define update behavior on certain fields.</description>
        <inlineHelpText>When this box is checked, the record is locked and certain fields cannot be edited</inlineHelpText>
        <label>Locked for Integration</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>Leaving this field empty, will automatically copy the IMCD Company value from the Account.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IntegrationId__c</fullName>
        <externalId>true</externalId>
        <label>IntegrationId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ImcdCompany__c.object
<CustomObject>
    <description>Custom Object used to store data specific to each IMCD company (see the IMCD global picklist). It is used (not only) for quote document generation purpose. It is related to user.</description>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <label>IMCD Company</label>
    <nameField>
        <label>IMCD Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMCD Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>DefaultCurrencyIsoCode__c</fullName>
        <label>Default Currency ISO Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntegrationId__c</fullName>
        <description>The IntegrationId__c will be prepopulated with the IMCD Company&apos;s api value</description>
        <externalId>true</externalId>
        <label>IntegrationId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PriceRenewalCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ContractedPriceIncrease__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Percent increase of contracted prices</inlineHelpText>
        <label>Contracted Price Increase</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PriceBook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The pricebook of the related Quotes or the Purchage prices</inlineHelpText>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Price Renewal Campaigns</relationshipLabel>
        <relationshipName>Price_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PricesToProcess__c</fullName>
        <label>Prices To Process</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Purchase</fullName>
                </value>
                <value>
                    <fullName>Contracted</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                    <label>All</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Responsible Product manager</inlineHelpText>
        <label>Product Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Price_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PurchasePriceIncrease__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Percent of increase for purchase Prices</inlineHelpText>
        <label>Purchase Price Increase</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Stage of campain.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Setup</fullName>
                    <color>#999999</color>
                    <default>true</default>
                    <label>Setup</label>
                </value>
                <value>
                    <fullName>Select</fullName>
                    <color>#78C953</color>
                    <label>Select</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                    <color>#3366FF</color>
                    <label>Review</label>
                </value>
                <value>
                    <fullName>Ready</fullName>
                    <color>#FFCC66</color>
                    <label>Ready</label>
                </value>
                <value>
                    <fullName>Queued</fullName>
                    <color>#FF0000</color>
                    <label>Queued</label>
                </value>
                <value>
                    <fullName>Processed</fullName>
                    <color>#33FF33</color>
                    <label>Processed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price Renewal Campaign</label>
    <nameField>
        <displayFormat>PRC-{000000}</displayFormat>
        <label>Price Renewal Campaign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Renewal Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>IntegrationId__c</fullName>
        <externalId>true</externalId>
        <label>Integration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ItemStatus__c</fullName>
        <description>Product item status</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>03.Active Pre Sales</fullName>
                    <label>Active Pre Sales</label>
                </value>
                <value>
                    <fullName>04.Active Sales</fullName>
                    <label>Active Sales</label>
                </value>
                <value>
                    <fullName>06.Inactive</fullName>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>01.New</fullName>
                    <label>New</label>
                </value>
                <value>
                    <fullName>07.Obsolete</fullName>
                    <label>Obsolete</label>
                </value>
                <value>
                    <fullName>05.Phase Out</fullName>
                    <label>Phase out</label>
                </value>
                <value>
                    <fullName>02.Temp Pre Sales</fullName>
                    <default>true</default>
                    <label>Temp Pre Sales</label>
                </value>
                <value>
                    <fullName>99.Rejected Temp</fullName>
                    <label>Rejected Temp</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <isActive>false</isActive>
                    <label>10</label>
                </value>
                <value>
                    <fullName>100</fullName>
                    <isActive>false</isActive>
                    <label>100</label>
                </value>
                <value>
                    <fullName>101</fullName>
                    <isActive>false</isActive>
                    <label>101</label>
                </value>
                <value>
                    <fullName>102</fullName>
                    <isActive>false</isActive>
                    <label>102</label>
                </value>
                <value>
                    <fullName>103</fullName>
                    <isActive>false</isActive>
                    <label>103</label>
                </value>
                <value>
                    <fullName>104</fullName>
                    <isActive>false</isActive>
                    <label>104</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <isActive>false</isActive>
                    <label>11</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <isActive>false</isActive>
                    <label>12</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <isActive>false</isActive>
                    <label>13</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <isActive>false</isActive>
                    <label>14</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <isActive>false</isActive>
                    <label>15</label>
                </value>
                <value>
                    <fullName>16</fullName>
                    <isActive>false</isActive>
                    <label>16</label>
                </value>
                <value>
                    <fullName>17</fullName>
                    <isActive>false</isActive>
                    <label>17</label>
                </value>
                <value>
                    <fullName>18</fullName>
                    <isActive>false</isActive>
                    <label>18</label>
                </value>
                <value>
                    <fullName>19</fullName>
                    <isActive>false</isActive>
                    <label>19</label>
                </value>
                <value>
                    <fullName>20</fullName>
                    <isActive>false</isActive>
                    <label>20</label>
                </value>
                <value>
                    <fullName>21</fullName>
                    <isActive>false</isActive>
                    <label>21</label>
                </value>
                <value>
                    <fullName>22</fullName>
                    <isActive>false</isActive>
                    <label>22</label>
                </value>
                <value>
                    <fullName>23</fullName>
                    <isActive>false</isActive>
                    <label>23</label>
                </value>
                <value>
                    <fullName>24</fullName>
                    <isActive>false</isActive>
                    <label>24</label>
                </value>
                <value>
                    <fullName>25</fullName>
                    <isActive>false</isActive>
                    <label>25</label>
                </value>
                <value>
                    <fullName>26</fullName>
                    <isActive>false</isActive>
                    <label>26</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LockedForIntegration__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Locked for Integration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProductManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <description>Standard product record type</description>
        <label>Product</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <description>Imcd Company for this user</description>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntegrationId__c</fullName>
        <description>Field containing the External Id for this user. Should be Unique.</description>
        <externalId>true</externalId>
        <inlineHelpText>Should be populated with the UserID of the originating ERP system.</inlineHelpText>
        <label>Integration Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CPQTestFactory.cls
/*
https://github.com/dhoechst/Salesforce-Test-Factory
// The TestFactory will pre-fill all the fields we typically need
Account a = (Account)CPQTestFactory.createSObject(new Account());
insert a;

*/


@isTest
public class CPQTestFactory {

    public static SObject createSObject(SObject sObj) {
        // Check what type of object we are creating and add any defaults that are needed.
        String objectName = String.valueOf(sObj.getSObjectType());
        // Construct the default values class. Salesforce doesn't allow '__' in class names
        String defaultClassName = 'CPQTestFactory.' + objectName.replaceAll('__(c|C)$|__', '') + 'Defaults';
  //      system.debug('------ defaultClassName '+defaultClassName);
        // If there is a class that exists for the default values, then use them
      if (Type.forName(defaultClassName) != null) {
          sObj = createSObject(sObj, defaultClassName);
      }
        return sObj;
    }

    public static SObject createSObject(SObject sObj, String defaultClassName) {
        // Create an instance of the defaults class so we can get the Map of field defaults
        Type t = Type.forName(defaultClassName);
        if (t == null) {
            throw new TestFactoryException('Invalid defaults class.');
        }
        FieldDefaults defaults = (FieldDefaults)t.newInstance();
        addFieldDefaults(sObj, defaults.getFieldDefaults());
        return sObj;
    }
    public class TestFactoryException extends Exception {}

    private static void addFieldDefaults(SObject sObj, Map<Schema.SObjectField, Object> defaults) {
        // Loop through the map of fields and if they weren't specifically assigned, fill them.
        Map<String, Object> populatedFields = sObj.getPopulatedFieldsAsMap();
        for (Schema.SObjectField field : defaults.keySet()) {
            if (!populatedFields.containsKey(String.valueOf(field))) {
                sObj.put(field, defaults.get(field));
            }
        }
    }

    // Use the FieldDefaults interface to set up values you want to default in for all objects.
    public interface FieldDefaults {
        Map<Schema.SObjectField, Object> getFieldDefaults();
    }

    public static SObject[] createSObjectList(Sobject sObj, Integer numberOfObjects, String defaultClassName) {
        SObject[] sObjs = new SObject[] {};
        SObject newObj;

        // Get one copy of the object
        if (defaultClassName == null) {
            newObj = createSObject(sObj);
        } else {
            newObj = createSObject(sObj, defaultClassName);
        }

        // Get the name field for the object
        String nameField = nameFieldMap.get(String.valueOf(sObj.getSObjectType()));
        if (nameField == null) {
            nameField = 'Name';
        }

        // Clone the object the number of times requested. Increment the name field so each record is unique
        for (Integer i = 0; i < numberOfObjects; i++) {
            SObject clonedSObj = newObj.clone(false, true);
            // we dont need this when the name field is an autonumber
            if (!sobj.getSObjectType().getDescribe().fields.getMap().get(nameField).getDescribe().isAutoNumber()) {
                clonedSObj.put(nameField, (String) clonedSObj.get(nameField) + ' ' + i);
            }
            sObjs.add(clonedSObj);
    
        }
        return sObjs;
    }
    // When we create a list of SObjects, we need to
    private static Map<String, String> nameFieldMap = new Map<String, String> {
            'Contact' => 'LastName',
            'Case' => 'Subject',
            'Lead' => 'LastName',
            'User' => 'LastName',
            'Account' => 'Description' 
    };

    public static SObject[] createSObjectList(Sobject sObj, Integer numberOfObjects) {
        return createSObjectList(sObj, numberOfObjects, (String)null);
    }

    public static SObject[] createSObjectList(SObject sObj, Integer numberOfObjects, Boolean doInsert) {
        SObject[] retList = createSObjectList(sObj, numberOfObjects, (String)null);
        if (doInsert) {
            insert retList;
        }
        return retList;
    }

    public static SObject[] createSObjectList(SObject sObj, Integer numberOfObjects, String defaultClassName, Boolean doInsert) {
        SObject[] retList = createSObjectList(sObj, numberOfObjects, defaultClassName);
        if (doInsert) {
            insert retList;
        }
        return retList;
    } 
    public class PriceRenewalCampaignDefaults implements FieldDefaults {
        public Map<Schema.SObjectField, Object> getFieldDefaults() {
            return new Map<Schema.SObjectField, Object> {
            PriceRenewalCampaign__c.PricesToProcess__c => 'All',
            PriceRenewalCampaign__c.PriceBook__c => Test.getStandardPricebookId(),
            PriceRenewalCampaign__c.PurchasePriceIncrease__c => 1,
            PriceRenewalCampaign__c.ContractedPriceIncrease__c => 1,
            PriceRenewalCampaign__c.Stage__c => 'Setup'
            };
        }
    }
    public class AccountDefaults implements FieldDefaults {
        public Map<Schema.SObjectField, Object> getFieldDefaults() {
            return new Map<Schema.SObjectField, Object> {
            Account.LockedForIntegration__c => false,
            Account.Name => 'TestName'
            };
        }
    }


    public class SBQQContractedPriceDefaults implements FieldDefaults {
        public Map<Schema.SObjectField, Object> getFieldDefaults() {
            return new Map<Schema.SObjectField, Object> {
            SBQQ__ContractedPrice__c.IntegrationId__c => 'SomeId'
            };
        }
    }
    public class Product2Defaults implements FieldDefaults {
        public Map<Schema.SObjectField, Object> getFieldDefaults() {
            return new Map<Schema.SObjectField, Object> {
            Product2.Name => 'Test Product',
            Product2.ItemStatus__c => '04.Active Sales',
            Product2.IsActive => true,
            Product2.ProductManager__c => Userinfo.getUserId()
            };
        }
    }

    public class Pricebook2Defaults implements FieldDefaults {
        public Map<Schema.SObjectField, Object> getFieldDefaults() {
            return new Map<Schema.SObjectField, Object> {
            Pricebook2.IsActive => true,
         
            Pricebook2.DefaultCurrencyIsoCode__c => 'EUR',
            Pricebook2.ImcdCompany__c => Pricebook2.ImcdCompany__c.getDescribe().getPicklistValues()[0].getValue(),
            Pricebook2.IntegrationId__c => Pricebook2.ImcdCompany__c.getDescribe().getPicklistValues()[0].getValue()
        
            };
        }
    }

 

}