objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_LOB1__c</fullName>
        <label>Primary LOB1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_LOB2__c</fullName>
        <label>Primary LOB2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_LOB3__c</fullName>
        <label>Primary LOB3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB3</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer_Prospect</fullName>
        <active>true</active>
        <description>Customer Prospect (CP)</description>
        <label>Customer Prospect</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AccountLob__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LOB Classifications</relationshipLabel>
        <relationshipName>LOB_Classifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LOB1__c</fullName>
        <label>LOB1</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOB2__c</fullName>
        <label>LOB2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>LOB1__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>LOB2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOB3__c</fullName>
        <label>LOB3</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>LOB2__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>LOB3</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>LOB Classification</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>LOB Classification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LOB Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/LOB1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advanced Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Coatings &amp; Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Food</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care and I&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Lubricants</fullName>
    </customValue>
    <customValue>
        <fullName>Other Specialties</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Care</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmaceuticals</fullName>
    </customValue>
    <customValue>
        <fullName>Synthesis</fullName>
    </customValue>
    <masterLabel>LOB1</masterLabel>
</GlobalValueSet>

globalValueSets/LOB2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adhesives &amp; Sealants</fullName>
    </customValue>
    <customValue>
        <fullName>Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Distributors</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial Coatings</fullName>
    </customValue>
    <customValue>
        <fullName>Inks</fullName>
    </customValue>
    <customValue>
        <fullName>Paints</fullName>
    </customValue>
    <customValue>
        <fullName>Animal Nutrition</fullName>
    </customValue>
    <customValue>
        <fullName>Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Beverage</fullName>
    </customValue>
    <customValue>
        <fullName>Confectionery</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Edible Oils &amp; Fats</fullName>
    </customValue>
    <customValue>
        <fullName>Fruits &amp; Vegetables</fullName>
    </customValue>
    <customValue>
        <fullName>Ingredients Manufacturers</fullName>
    </customValue>
    <customValue>
        <fullName>Nutrition</fullName>
    </customValue>
    <customValue>
        <fullName>Savoury</fullName>
    </customValue>
    <customValue>
        <fullName>Distributors &amp; Traders</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care</fullName>
    </customValue>
    <customValue>
        <fullName>I&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Drilling fluids</fullName>
    </customValue>
    <customValue>
        <fullName>Driveline fluids</fullName>
    </customValue>
    <customValue>
        <fullName>Engine oils</fullName>
    </customValue>
    <customValue>
        <fullName>Fuel Additives</fullName>
    </customValue>
    <customValue>
        <fullName>Fuels</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial oils</fullName>
    </customValue>
    <customValue>
        <fullName>Lubricants</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>High Temperature Products</fullName>
    </customValue>
    <customValue>
        <fullName>Lab Instruments</fullName>
    </customValue>
    <masterLabel>LOB2</masterLabel>
</GlobalValueSet>

globalValueSets/LOB3.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Consumer and Professional</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Label &amp; Tape</fullName>
    </customValue>
    <customValue>
        <fullName>Packaging</fullName>
    </customValue>
    <customValue>
        <fullName>Bitumen Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Technologies</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Mortars</fullName>
    </customValue>
    <customValue>
        <fullName>Floor Coverings</fullName>
    </customValue>
    <customValue>
        <fullName>Masonry &amp; Wall Products</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Can &amp; Coil</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <customValue>
        <fullName>Plastics</fullName>
    </customValue>
    <customValue>
        <fullName>Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Wood</fullName>
    </customValue>
    <customValue>
        <fullName>Flexo &amp; Gravure</fullName>
    </customValue>
    <customValue>
        <fullName>Inkjet &amp; Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Offset</fullName>
    </customValue>
    <customValue>
        <fullName>Overprint Varnish</fullName>
    </customValue>
    <customValue>
        <fullName>Screen Printing</fullName>
    </customValue>
    <customValue>
        <fullName>Distributors &amp; Traders</fullName>
    </customValue>
    <customValue>
        <fullName>Feed</fullName>
    </customValue>
    <customValue>
        <fullName>Pet Food</fullName>
    </customValue>
    <customValue>
        <fullName>Blenders &amp; Improvers</fullName>
    </customValue>
    <customValue>
        <fullName>Bread</fullName>
    </customValue>
    <customValue>
        <fullName>Cereals &amp; Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Fine Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Milling &amp; Flour</fullName>
    </customValue>
    <customValue>
        <fullName>Beer &amp; Brewing</fullName>
    </customValue>
    <customValue>
        <fullName>Powder Drinks</fullName>
    </customValue>
    <customValue>
        <fullName>Diesel additives</fullName>
    </customValue>
    <masterLabel>LOB3</masterLabel>
</GlobalValueSet>

classes/TestAccountLobTrigger.cls
@isTest
public class TestAccountLobTrigger {
    /* Tests four LOB Classification (LOBC) scenarios:
     * 1. insertNonPrimary(): Error when first LOBC is non-primary.
     * 2. insertTwoPrimaries(): First primary LOBC is automatically unmarked
     *    as primary when second one is inserted.
     * 3. deletePrimaryLOB(): Error when primary LOBC is deleted.
     * 4. accountFields(): Account's 'Primary LOB' fields are updated when
     *                     inserting a new primary LOBC.
     */
    
    @testSetup static void setup() {
        
        // Create test User, Account and AccountLOB.
        List<User> users = TestDataFactory.createUsers(1, Label.Standard_User_Profile_Name, '21100');
		List<Account> accounts = TestDataFactory.createAccounts(1, 'Customer_Prospect', users[0].Id, '21100');
        TestDataFactory.createBypassCustomSetting();
        
    }
    
    /* Insert a non-primary LOBC as the first LOBC for the Account.
     * Expected behavior: an error will be returned, because at least
	   one primary LOBC is required. */
    @isTest static void testInsertNonPrimary() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        
        AccountLob__c lobC = new AccountLob__c(Account__c = account.Id, LOB1__c = 'Lubricants', LOB2__c = 'Fuels', LOB3__c = 'Diesel additives');
        
        Test.startTest();
        try {
      		insert lobC;
        }
        catch(DMLException e) {
            System.assertEquals(Label.ERROR_LOB_MUST_BE_PRIMARY, e.getDmlMessage(0));
        }
        Test.stopTest();
    }
    
    /* Try to insert two primary LOBCs for one Account.
     * Expected behavior: after insertion of the second LOBC,
     * the first one is automatically unmarked as primary. */
    @isTest static void testInsertTwoPrimaries() {
        System.runAs([SELECT Id FROM User LIMIT 1][0]) {
            Account account = [SELECT Id FROM Account LIMIT 1];
            
            List<AccountLob__c> lobCList = new List<AccountLob__c>();
    
            // Add two primary LOB Classifications for the same Account.
            lobCList.add(new AccountLob__c(Account__c = account.Id, Primary__c = TRUE, LOB1__c = 'Lubricants'));
            lobCList.add(new AccountLob__c(Account__c = account.Id, Primary__c = TRUE, LOB1__c = 'Lubricants', LOB2__c = 'Fuels'));
            
        	// Push LOB Classifications to database and get their IDs.
            Test.startTest();
            Database.SaveResult[] insertResults = Database.insert(lobCList);
            Test.stopTest();
        
        	List<ID> lobCIds = new List<ID>();
        
            for (Database.SaveResult result : insertResults) {
                if (result.isSuccess()) {
                    lobCIds.add(result.getId());
                }
            }
            
            System.debug('lobCIds ' + lobCIds);
               
            // Query recently pushed LOB Classifications to see if only one is still primary.
            List<AccountLob__c> accLobs = [SELECT Id, Primary__c
                                           FROM AccountLob__c
                                           WHERE Id in :lobCIds];
            
            Integer primaryCounter = 0;
            
            System.debug('accLobs ' + accLobs);
            
            for (AccountLob__c accLob : accLobs) {
                if (accLob.Primary__c == TRUE) primaryCounter++;
            }
            
            System.assertEquals(1, primaryCounter);
        }
    }
    
    /* Insert a new primary LOBC, and then delete it.
     * Expected behavior: error because primary LOB cannot
     * be deleted. */
    @isTest static void testDeletePrimaryLOB() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        
        AccountLob__c lobC = new AccountLob__c(Account__c = account.Id, LOB1__c = 'Lubricants', LOB2__c = 'Fuels', LOB3__c = 'Diesel additives', Primary__c = TRUE);
        
        Test.startTest();
      	insert lobC;
        try {
        	delete lobC;
        } catch(DmlException e) {
            System.assertEquals(Label.ERROR_CANT_DELETE_PRIMARY, e.getDmlMessage(0));
        }
        Test.stopTest();
    }
    
    @isTest static void testAccountFields() {
        System.runAs([SELECT Id FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1][0]) {
            Account account = [SELECT Id FROM Account LIMIT 1];
            
            AccountLob__c lobC = new AccountLob__c(Account__c = account.Id, Primary__c = TRUE, LOB1__c = 'Lubricants', LOB2__c = 'Fuels', LOB3__c = 'Diesel additives');
            
            Test.startTest();
            insert lobC;
            Test.stopTest();
            
            account = [SELECT Id, Primary_LOB1__c, Primary_LOB2__c, Primary_LOB3__c FROM Account WHERE Id =: account.Id LIMIT 1][0];
            
            System.assertEquals('Lubricants', account.Primary_LOB1__c);
            System.assertEquals('Fuels', account.Primary_LOB2__c);
            System.assertEquals('Diesel additives', account.Primary_LOB3__c);
        }
    }
}