objects/Account.object
<CustomObject>
    <fields>
        <fullName>LockedForIntegration__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating when a Prospect has been sent for Integration. When Checkbox is set, Validation rules define update behavior on certain fields.</description>
        <inlineHelpText>When this box is checked, the record is locked and certain fields cannot be edited</inlineHelpText>
        <label>Locked for Integration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_LOB1__c</fullName>
        <label>Primary LOB1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_LOB2__c</fullName>
        <label>Primary LOB2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_LOB3__c</fullName>
        <label>Primary LOB3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB3</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer_Prospect</fullName>
        <active>true</active>
        <description>Customer Prospect (CP)</description>
        <label>Customer Prospect</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AccountLob__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LOB Classifications</relationshipLabel>
        <relationshipName>LOB_Classifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LOB1__c</fullName>
        <label>LOB1</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOB2__c</fullName>
        <label>LOB2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>LOB1__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>LOB2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOB3__c</fullName>
        <label>LOB3</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>LOB2__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>LOB3</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>LOB Classification</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>LOB Classification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LOB Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IntegrationLog__c.object
<CustomObject>
    <description>This object stores records which require integration. The object triggers in turn Outbound Messages when required. The object also acts as mechanism to track records requiring ETL-based integrations for non-group ERP countries.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Integration Logs</relationshipLabel>
        <relationshipName>Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>INT{000000000}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/LOB1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advanced Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Coatings &amp; Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Food</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care and I&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Lubricants</fullName>
    </customValue>
    <customValue>
        <fullName>Other Specialties</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Care</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmaceuticals</fullName>
    </customValue>
    <customValue>
        <fullName>Synthesis</fullName>
    </customValue>
    <masterLabel>LOB1</masterLabel>
</GlobalValueSet>

globalValueSets/LOB2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adhesives &amp; Sealants</fullName>
    </customValue>
    <customValue>
        <fullName>Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Distributors</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial Coatings</fullName>
    </customValue>
    <customValue>
        <fullName>Inks</fullName>
    </customValue>
    <customValue>
        <fullName>Paints</fullName>
    </customValue>
    <customValue>
        <fullName>Animal Nutrition</fullName>
    </customValue>
    <customValue>
        <fullName>Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Beverage</fullName>
    </customValue>
    <customValue>
        <fullName>Confectionery</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Edible Oils &amp; Fats</fullName>
    </customValue>
    <customValue>
        <fullName>Fruits &amp; Vegetables</fullName>
    </customValue>
    <customValue>
        <fullName>Ingredients Manufacturers</fullName>
    </customValue>
    <customValue>
        <fullName>Nutrition</fullName>
    </customValue>
    <customValue>
        <fullName>Savoury</fullName>
    </customValue>
    <customValue>
        <fullName>Distributors &amp; Traders</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care</fullName>
    </customValue>
    <customValue>
        <fullName>I&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Drilling fluids</fullName>
    </customValue>
    <customValue>
        <fullName>Driveline fluids</fullName>
    </customValue>
    <customValue>
        <fullName>Engine oils</fullName>
    </customValue>
    <customValue>
        <fullName>Fuel Additives</fullName>
    </customValue>
    <customValue>
        <fullName>Fuels</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial oils</fullName>
    </customValue>
    <customValue>
        <fullName>Lubricants</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>High Temperature Products</fullName>
    </customValue>
    <customValue>
        <fullName>Lab Instruments</fullName>
    </customValue>
    <masterLabel>LOB2</masterLabel>
</GlobalValueSet>

globalValueSets/LOB3.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Consumer and Professional</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Label &amp; Tape</fullName>
    </customValue>
    <customValue>
        <fullName>Packaging</fullName>
    </customValue>
    <customValue>
        <fullName>Bitumen Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Technologies</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Mortars</fullName>
    </customValue>
    <customValue>
        <fullName>Floor Coverings</fullName>
    </customValue>
    <customValue>
        <fullName>Masonry &amp; Wall Products</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Can &amp; Coil</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <customValue>
        <fullName>Plastics</fullName>
    </customValue>
    <customValue>
        <fullName>Powder</fullName>
    </customValue>
    <customValue>
        <fullName>Wood</fullName>
    </customValue>
    <customValue>
        <fullName>Flexo &amp; Gravure</fullName>
    </customValue>
    <customValue>
        <fullName>Inkjet &amp; Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Offset</fullName>
    </customValue>
    <customValue>
        <fullName>Overprint Varnish</fullName>
    </customValue>
    <customValue>
        <fullName>Screen Printing</fullName>
    </customValue>
    <customValue>
        <fullName>Distributors &amp; Traders</fullName>
    </customValue>
    <customValue>
        <fullName>Feed</fullName>
    </customValue>
    <customValue>
        <fullName>Pet Food</fullName>
    </customValue>
    <customValue>
        <fullName>Blenders &amp; Improvers</fullName>
    </customValue>
    <customValue>
        <fullName>Bread</fullName>
    </customValue>
    <customValue>
        <fullName>Cereals &amp; Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Fine Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Milling &amp; Flour</fullName>
    </customValue>
    <customValue>
        <fullName>Beer &amp; Brewing</fullName>
    </customValue>
    <customValue>
        <fullName>Powder Drinks</fullName>
    </customValue>
    <masterLabel>LOB3</masterLabel>
</GlobalValueSet>

classes/TestSubmitProspectController.cls
/*------------------------------------------------------------  
Author:        Jeroen Burgers   
Company:       Salesforce   
User Story:    
History 
05/11/2018     Created class
------------------------------------------------------------*/  
@isTest
private class TestSubmitProspectController {

    @testsetup
    public static void testsetup() {
        // enable AccountLob__c triggers
        TestDataFactoryUtils.runTriggers(true);
        TestDataFactoryUtils.runProcessBuilders(true);
        List<User> users = TestDataFactory.createUsers(1, Label.Standard_User_Profile_Name, '21100');
        // passing in null for IMCDCompany, should be set by BP (part of test)
        List<Account> accounts;
        System.runAs(users[0])
        {
            accounts = TestDataFactory.createAccounts(1, 'Customer_Prospect', users[0].Id, null);
        }
        // Don't care about dependencies of LOB's - just have random LOBs picked
        List<AccountLob__c> lobs = TestDataFactory.createAccountLobs(1, accounts);
        // Create IntegrationLog__c record
        List<IntegrationLog__c> intlogs = TestDataFactory.createIntegrationLogs(1, 'Queued', 'CREATE_CUSTOMER');
        // Update Account__c Lookup
        IntegrationLog__c intLog = [SELECT Id FROM IntegrationLog__c LIMIT 1];
        intLog.Account__c = accounts[0].Id;
        update intLog;
        // Create custom settings
        TestDataFactory.createIntegrationSettings();
    }

    @isTest
    static void testPrimaryLob () {
        List<AccountLob__c> lstLob = [SELECT LOB1__c, LOB2__c, LOB3__c, Account__c FROM AccountLob__c WHERE Primary__c = True LIMIT 1];
        List<Account> lstAccount = [SELECT Primary_LOB1__c , Primary_LOB2__c , Primary_LOB3__c FROM Account WHERE Id =: lstLob[0].Account__c LIMIT 1];
        System.assert(lstLob[0].LOB1__c == lstAccount[0].Primary_LOB1__c &&
                      lstLob[0].LOB2__c == lstAccount[0].Primary_LOB2__c &&
                      lstLob[0].LOB3__c == lstAccount[0].Primary_LOB3__c, 'Primary LOB values are not copied from related AccountLob__c related lists');
    }
    
    @isTest
    static void testGetData () {
        List<Account> lstAccount = [SELECT Id FROM Account LIMIT 1];
        Map<String, Object> data = SubmitProspectController.getData(lstAccount[0].Id);
        System.assertEquals(data.get('Id'), lstAccount[0].Id, 'One prospect should be returned');
    }    

    @isTest
    static void testHasActiveIntegration () {
        List<Account> lstAccount = [SELECT Id FROM Account LIMIT 1];
        Boolean hasIntegration = SubmitProspectController.hasActiveIntegration(lstAccount[0].Id);
        System.assertEquals(True, hasIntegration, 'Should have Integration');
    }    
    
    @isTest
    static void testCreateIntegrationLog () {
        // Tests for normal situation where user does not have the SfManagedAccounts permission
        List<Account> lstAccount = [SELECT Id FROM Account LIMIT 1];
        Boolean result = SubmitProspectController.CreateIntegrationLog(lstAccount[0].Id);
        System.assertEquals(True, result, 'Calling CreateIntegrationLog should return success');
        
        //setting up for failure, class uses if (Test.isRunningTest() && accnt.LockedForIntegration__c) condition
        lstAccount[0].LockedForIntegration__c = true;
        update lstAccount;
        result = SubmitProspectController.CreateIntegrationLog(lstAccount[0].Id);
        System.assertEquals(False, result, 'Calling CreateIntegrationLog should fail');
    }

    @isTest
    static void testconvertSoldtoAccount () {
        // Tests for situation where user does have the SfManagedAccounts permission
        List<Account> lstAccount = [SELECT Id FROM Account LIMIT 1];
        Boolean result = SubmitProspectController.convertSoldtoAccount(lstAccount[0].Id, '99999');
        System.assertEquals(True, result, 'Calling convertProspect should return success');
    }
    
}