objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>This value will be set based on the IMCD Company of your User.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>ExternalComments__c</fullName>
        <description>Field used for external comments on the Sample request document</description>
        <label>External Comments</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>Leaving this field empty, will automatically copy the IMCD Company value from the Account.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>InternalComments__c</fullName>
        <label>Internal Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LOB1__c</fullName>
        <label>LOB1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrincipalId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Principal</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You have to select a global principal record.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Principal_Global</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FollowUpReport__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>This field can contain up to 1024 characters. External Comments from multiple Follow-up reports are summarized and can be exported using a report.</inlineHelpText>
        <label>External Comments</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>InternalComments__c</fullName>
        <label>Internal Comments</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>QuoteLine__c</fullName>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Follow-up Reports</relationshipLabel>
        <relationshipName>Follow_up_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Follow-up Report</label>
    <nameField>
        <displayFormat>FUR-{000000000}</displayFormat>
        <label>Follow-up Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow-up Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FollowupReportSummary__c.object
<CustomObject>
    <description>https://imcdgroup.atlassian.net/browse/SFDP-2223

Master-detail from SBQQ__QuoteLine__c holding max a single record per Quote line. 
FollowupReportSummary__c will contain concatenated FollowupReport__c records (via automation)
Object not exposed to user, only through Reporting
Name will contain related SBQQ__QuoteLine__c 
Validation rule to ensure uniqueness of Name</description>
    <fields>
        <fullName>CreatedByAudit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Instead of CreatedById, this field identifies the User who created the most recent Follow-up report against the Quote Line.</description>
        <label>Created By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CreatedByFollowupReportSummaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalComments__c</fullName>
        <label>External Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>InternalComments__c</fullName>
        <label>Internal Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>LastFollowupReport__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Last Follow-up Report</label>
        <referenceTo>FollowUpReport__c</referenceTo>
        <relationshipLabel>Follow-up Report Summaries</relationshipLabel>
        <relationshipName>Follow_up_Report_Summaries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LastModifiedByAudit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Instead of LastModifiedById, this field identifies the User who updated one of the Follow-up reports consistituating this Follow-up ReportSummary.</description>
        <label>Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>LastModifedByFollowupReportSummaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuoteLine__c</fullName>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Follow-up Report Summaries</relationshipLabel>
        <relationshipName>FollowupReportSummaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Follow-up Report Summary</label>
    <nameField>
        <label>Follow-up Report Summary Quote Line Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Follow-up Report Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Global_Bypass_Processes_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global Bypass Control Panel</description>
    <label>Global Bypass Processes Settings</label>
</CustomObject>

objects/ImcdCompany__c.object
<CustomObject>
    <description>Custom Object used to store data specific to each IMCD company (see the IMCD global picklist). It is used (not only) for quote document generation purpose. It is related to user.</description>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <label>IMCD Company</label>
    <nameField>
        <label>IMCD Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMCD Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/MarketInfoBO__c.object
<CustomObject>
    <fields>
        <fullName>QuoteLine__c</fullName>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Market Info BO</relationshipLabel>
        <relationshipName>Market_Info_BO</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Market Info BO</label>
    <nameField>
        <displayFormat>MB-{000000000}</displayFormat>
        <label>Market Info BO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Info BO</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LOB1__c</fullName>
        <inlineHelpText>Leaving this field empty, will automatically copy the Primary LOB1/2/3 values from the Account</inlineHelpText>
        <label>LOB1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <description>Standard product record type</description>
        <label>Product</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
</CustomObject>

objects/SharingAccess__c.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOB1__c</fullName>
        <label>LOB1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrincipalId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Principal</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a Principal Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Principal Global</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>SharingAcees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sharing Access</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sharing Access</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <description>Imcd Company for this user</description>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/LOB1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advanced Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Coatings &amp; Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Food</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care and I&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Lubricants</fullName>
    </customValue>
    <customValue>
        <fullName>Other Specialties</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Care</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmaceuticals</fullName>
    </customValue>
    <customValue>
        <fullName>Synthesis</fullName>
    </customValue>
    <masterLabel>LOB1</masterLabel>
</GlobalValueSet>

classes/TestQuoteLineItemTriggerHelper.cls
/******************************************************************************************************************************************************************
 * Author: Aviad Efergan, Eli Pogorelov
 * Company: Salesforce
 * Description: Tests for TestQuoteLineItemTriggerHelper
 * History :
 ******************************************************************************************************************************************************************/
@isTest
private class TestQuoteLineItemTriggerHelper {

	@testSetup
	static void createTestData() {

		list<Account> soldToAccounts = TestDataFactory.createAccounts(1, Label.Customer_Sold_To_Account_Record_Type, TestDataFactoryUtils.getContextUserId(), '79100');
		soldToAccounts.addAll(TestDataFactory.createAccounts(1, Label.Customer_Sold_To_Account_Record_Type, TestDataFactoryUtils.getContextUserId(), '13100'));

		soldToAccounts.addAll(TestDataFactory.createAccounts(1, Label.Customer_Sold_To_Account_Record_Type, TestDataFactoryUtils.getContextUserId(), '91100'));
		list<Account> regionAccounts = TestDataFactory.createAccounts(3, Label.Global_Principa_Account_RecordType, TestDataFactoryUtils.getContextUserId(), '13100');

		for (Integer i = 0; i < soldToAccounts.size(); i++) {
			soldToAccounts[i].ParentId = regionAccounts[i].Id;
		}

		update soldToAccounts;

		list<SBQQ__Quote__c> qtLst = TestDataFactory.returnQuotes(1, soldToAccounts[0], new List<String>{'Coatings & Construction'});
		qtLst.addAll(TestDataFactory.returnQuotes(1, soldToAccounts[1], new List<String>{'Food'}));
		qtLst.addAll(TestDataFactory.returnQuotes(1, soldToAccounts[2], new List<String>{'Lubricants'}));
		insert qtLst;

		list<User> usersLst = TestDataFactory.createUsers(1, Label.Standard_User_Profile_Name, '79100');
		list<User> usersLst2 = TestDataFactory.createUsers(1, Label.Standard_User_Profile_Name, '79100');
		list<SharingAccess__c> shareAccsLst = TestDataFactory.getSharingAccessList(usersLst, '79100', 'Coatings & Construction', false);
		shareAccsLst[0].PrincipalId__c = regionAccounts[0].Id;
		shareAccsLst.addAll(TestDataFactory.getSharingAccessList(usersLst, '79100', 'Food', true));
		shareAccsLst[1].PrincipalId__c = regionAccounts[0].Id;
		shareAccsLst.addAll(TestDataFactory.getSharingAccessList(usersLst, '79100', 'Lubricants', false));
		shareAccsLst[2].PrincipalId__c = regionAccounts[0].Id;
		shareAccsLst.addAll(TestDataFactory.getSharingAccessList(usersLst2, '79100', '', true));
		shareAccsLst[3].PrincipalId__c = regionAccounts[0].Id;
		shareAccsLst.addAll(TestDataFactory.getSharingAccessList(usersLst2, '79100', '', false));
		shareAccsLst[4].PrincipalId__c = regionAccounts[0].Id;
		insert shareAccsLst;

		Product2 prod = TestDataFactory.createProduct(regionAccounts[0].Id);

		//Global_Bypass_Processes_Settings__c cs = TestDataFactory.createBypassCustomSetting();
		TestDataFactoryUtils.runTriggers(true);
		TestDataFactoryUtils.runProcessBuilders(false);

		TestDataFactory.createRecordTypeIds();

		List<String> imcdCompaniesForTest = new List<String>{'79100','13100','91100'};
		TestDataFactory.createImcdCompanies(imcdCompaniesForTest);
	}

	@isTest
	static void test_Setup() {
		System.assertEquals(6, [SELECT Id FROM Account].size(), 'Six Account records should have been created in the testSetup');
		System.assertEquals(3, [SELECT Id FROM SBQQ__Quote__c].size(), 'Three SBQQ__Quote__c records should have been created in the testSetup');
//		System.assertEquals(1, [SELECT Id FROM User WHERE IMCDCompany__c='79100' AND alias = 'test1'].size(), 'A single user record for company 79100 should have been created in the testSetup');
// Changed check from 1 to 2 WvB 25-9-2018
		System.assertEquals(2, [SELECT Id FROM User WHERE IMCDCompany__c='79100' AND alias = 'test1'].size(), 'A single user record for company 79100 should have been created in the testSetup');
		System.assertEquals(1, [SELECT Id FROM Product2].size(), 'A single Product record should have been created in the testSetup');
	}

	@isTest
	static void test_accountShareBasedOppLineItem_match() {
		Test.startTest();
		Product2 prod = [Select Id from Product2 limit 1];
		list<SBQQ__Quote__c> qtLst = [Select Id, SBQQ__Account__c, SBQQ__Account__r.ParentId  From SBQQ__Quote__c Where SBQQ__Account__r.ImcdCompany__c = '79100' And LOB1__c = 'Coatings & Construction'];
		list<SBQQ__QuoteLine__c> qtLineLst = TestDataFactory.returnQuoteLine(1, qtLst[0].Id, prod.Id);
		Test.stopTest();

		insert qtLineLst;
//        System.assertEquals(0, TestDataFactory.numDebugErrors(), TestDataFactory.getDebugErrors());

		Id sharedUserId = [Select Id From User Where Profile.Name =: Label.Standard_User_Profile_Name and ImcdCompany__c = '79100' limit 1].Id;
		//Assert correct share match by LOB, Company and Principal to Quote
//		System.assert([Select UserOrGroupId From SBQQ__Quote__Share Where ParentId =: qtLst[0].Id and UserOrGroupId =: sharedUserId].size() > 0, 'There should have been SBQQ__Quote__Share records');
		//Assert match soldTo and regional account
//		System.assert([Select UserOrGroupId From AccountShare Where AccountId =: qtLst[0].SBQQ__Account__c and UserOrGroupId =: sharedUserId].size() > 0);
//		System.assert([Select UserOrGroupId From AccountShare Where AccountId =: qtLst[0].SBQQ__Account__r.ParentId and UserOrGroupId =: sharedUserId].size() > 0); 
	}

	@isTest
	static void test_accountShareBasedOppLineItem_match_global() {
		Test.startTest();
		Product2 prod = [Select Id from Product2 limit 1];
		list<SBQQ__Quote__c> qtLst = [Select Id, SBQQ__Account__c, SBQQ__Account__r.ParentId  From SBQQ__Quote__c Where SBQQ__Account__r.ImcdCompany__c = '13100' And LOB1__c = 'Food'];
		list<SBQQ__QuoteLine__c> qtLineLst = TestDataFactory.returnQuoteLine(1, qtLst[0].Id, prod.Id);
		Test.stopTest();

		insert qtLineLst;
//		System.assertEquals(0, TestDataFactory.numDebugErrors(), TestDataFactory.getDebugErrors());

		Id sharedUserId = [Select Id From User Where Profile.Name =: Label.Standard_User_Profile_Name and ImcdCompany__c = '79100' limit 1].Id;
		//Assert correct share match by LOB, Company and Principal to Opportunity
//		System.assert([Select UserOrGroupId From SBQQ__Quote__Share Where ParentId =: qtLst[0].Id and UserOrGroupId =: sharedUserId].size() > 0);
		//Assert match soldTo and regional account
//		System.assert([Select UserOrGroupId From AccountShare Where AccountId =: qtLst[0].SBQQ__Account__c and UserOrGroupId =: sharedUserId].size() > 0);
//		System.assert([Select UserOrGroupId From AccountShare Where AccountId =: qtLst[0].SBQQ__Account__r.ParentId and UserOrGroupId =: sharedUserId].size() > 0);
	}

	@isTest
	static void test_accountShareBasedOppLineItem_no_match() {
		Test.startTest();
		Product2 prod = [Select Id from Product2 limit 1];
		list<SBQQ__Quote__c> qtLst = [Select Id, SBQQ__Account__c, SBQQ__Account__r.ParentId  From SBQQ__Quote__c Where SBQQ__Account__r.ImcdCompany__c = '91100' And LOB1__c = 'Lubricants'];
		list<SBQQ__QuoteLine__c> qtLineLst = TestDataFactory.returnQuoteLine(1, qtLst[0].Id, prod.Id);
		Test.stopTest();

		insert qtLineLst;

		Id sharedUserId = [Select Id From User Where Profile.Name =: Label.Standard_User_Profile_Name and ImcdCompany__c = '79100' limit 1].Id;
		//Assert no share match by LOB, Company and Principal to Opportunity
		System.assert([Select UserOrGroupId From SBQQ__Quote__Share Where ParentId =: qtLst[0].Id and UserOrGroupId =: sharedUserId].size() == 0);
		//Assert no match soldTo and regional account
		System.assert([Select UserOrGroupId From AccountShare Where AccountId =: qtLst[0].SBQQ__Account__c and UserOrGroupId =: sharedUserId].size() == 0);
		System.assert([Select UserOrGroupId From AccountShare Where AccountId =: qtLst[0].SBQQ__Account__r.ParentId and UserOrGroupId =: sharedUserId].size() == 0);
	}

	@isTest
	static void test_IsQuoteLineItemNotDeletedIFChildRecordsCaseExists(){

		Product2 product = [Select Id from Product2 limit 1];
		List<SBQQ__Quote__c> quoteList = [Select Id, SBQQ__Account__c, SBQQ__Account__r.ParentId  From SBQQ__Quote__c Where SBQQ__Account__r.ImcdCompany__c = '91100' And LOB1__c = 'Lubricants'];
		List<SBQQ__QuoteLine__c> quoteLineList = TestDataFactory.returnQuoteLine(1, quoteList[0].Id, product.Id);
		insert quoteLineList;
		Case testCase = new Case(QuoteLine__c = quoteLineList[0].Id);
		insert testCase;
		Test.startTest();
        	try
            {
            	delete quoteLineList[0];
            }
        	catch(Exception ex)
        	{
                String exMsg = ex.getMessage().substringBetween('FIELD_CUSTOM_VALIDATION_EXCEPTION,',': []').trim();
            	System.assertEquals(String.valueOf(Label.prevent_delete_of_Quote_Line_Case_scenario), String.valueOf(exMsg));
        	}
		Test.stopTest();        
	}
    
    @isTest
	static void test_IsQuoteLineItemNotDeletedIFChildRecordsMInfoExists(){

		Product2 product = [Select Id from Product2 limit 1];
		List<SBQQ__Quote__c> quoteList = [Select Id, SBQQ__Account__c, SBQQ__Account__r.ParentId  From SBQQ__Quote__c Where SBQQ__Account__r.ImcdCompany__c = '91100' And LOB1__c = 'Lubricants'];
		List<SBQQ__QuoteLine__c> quoteLineList = TestDataFactory.returnQuoteLine(1, quoteList[0].Id, product.Id);
		insert quoteLineList;
		MarketInfoBO__c marketInfoBO = new MarketInfoBO__c(QuoteLine__c = quoteLineList[0].Id);
		insert marketInfoBO;
		Test.startTest();
        	try
            {
            	delete quoteLineList[0];
            }
        	catch(Exception ex)
        	{
                String exMsg = ex.getMessage().substringBetween('FIELD_CUSTOM_VALIDATION_EXCEPTION,',': []').trim();
            	System.assertEquals( String.valueOf(Label.prevent_delete_of_Quote_Line_MInfo_scenario), String.valueOf(exMsg));
        	}
		Test.stopTest();        
	}
    
    @isTest
	static void test_IsQuoteLineItemNotDeletedIFChildRecordsFreportExists(){

		Product2 product = [Select Id from Product2 limit 1];
		List<SBQQ__Quote__c> quoteList = [Select Id, SBQQ__Account__c, SBQQ__Account__r.ParentId  From SBQQ__Quote__c Where SBQQ__Account__r.ImcdCompany__c = '91100' And LOB1__c = 'Lubricants'];
		List<SBQQ__QuoteLine__c> quoteLineList = TestDataFactory.returnQuoteLine(1, quoteList[0].Id, product.Id);
		insert quoteLineList;
		FollowUpReport__c followUpReport = new FollowUpReport__c(QuoteLine__c = quoteLineList[0].Id);
		insert followUpReport;
		Test.startTest();
        	try
            {
            	delete quoteLineList[0];
            }
        	catch(Exception ex)
        	{
                String exMsg = ex.getMessage().substringBetween('FIELD_CUSTOM_VALIDATION_EXCEPTION,',': []').trim();
            	System.assertEquals(String.valueOf(Label.prevent_delete_of_Quote_Line_FReports_scenario), String.valueOf(exMsg));
        	}
		Test.stopTest();        
	}

	@isTest
	static void test_IsQuoteLineItemDeletedIFChildRecordsDoNotExist(){

		Product2 product = [Select Id from Product2 limit 1];
		List<SBQQ__Quote__c> quoteList = [Select Id, SBQQ__Account__c, SBQQ__Account__r.ParentId  From SBQQ__Quote__c Where SBQQ__Account__r.ImcdCompany__c = '91100' And LOB1__c = 'Lubricants'];
		List<SBQQ__QuoteLine__c> quoteLineList = TestDataFactory.returnQuoteLine(1, quoteList[0].Id, product.Id);
		insert quoteLineList;
		Test.startTest();
			delete quoteLineList[0];
		Test.stopTest();
		System.assertEquals(0, [SELECT count() FROM SBQQ__QuoteLine__c WHERE ID =: quoteLineList[0].ID]);
	}

	@isTest
	static void test_IsQuoteLineItemDeleted_IF_Orig_Qt_OnContractPriceExist(){

		Product2 product = [Select Id from Product2 limit 1];
		List<Product2> prodList = new List<Product2>{product};
		List<SBQQ__Quote__c> quoteList = [Select Id, SBQQ__Account__c, SBQQ__Account__r.ParentId  From SBQQ__Quote__c Where SBQQ__Account__r.ImcdCompany__c = '91100' And LOB1__c = 'Lubricants'];
		List<SBQQ__QuoteLine__c> quoteLineList = TestDataFactory.returnQuoteLine(1, quoteList[0].Id, product.Id);
		insert quoteLineList;
		List<Account> accList = new List<Account>([SELECT Id From Account limit 1]);
		List<SBQQ__ContractedPrice__c> contractedPrices = TestDataFactory.createContractedPrices(1, accList[0], prodList);
		contractedPrices[0].SBQQ__OriginalQuoteLine__c = quoteLineList[0].Id ;
		update contractedPrices;
		Test.startTest();
		try
		{
			delete quoteLineList[0];
		}
		catch(Exception ex)
		{
			String exMsg = ex.getMessage().substringBetween('FIELD_CUSTOM_VALIDATION_EXCEPTION,',': []').trim();
			System.assertEquals(String.valueOf(Label.prevent_delete_of_Quote_Line_ContPrice_Scenario), String.valueOf(exMsg));
		}
		Test.stopTest();
	}

	@IsTest
	private static void testFollowupReportSummaryCompController() {
		// Test method here, because it would be to cumbesome to repeat all data setup
		Product2 prod = [Select Id from Product2 limit 1];
		List<SBQQ__Quote__c> qtLst = [Select Id, SBQQ__Account__c, SBQQ__Account__r.ParentId  From SBQQ__Quote__c Where SBQQ__Account__r.ImcdCompany__c = '91100' And LOB1__c = 'Lubricants'];
		List<SBQQ__QuoteLine__c> qtLineLst = TestDataFactory.returnQuoteLine(1, qtLst[0].Id, prod.Id);
		insert qtLineLst;
		FollowUpReport__c followUpReport = new FollowUpReport__c(Description__c = 'last follow-up report', QuoteLine__c = qtLineLst[0].Id);
		insert followUpReport;
		FollowupReportSummary__c followupReportSummary =
				new FollowupReportSummary__c(ExternalComments__c = 'bogus', InternalComments__c = 'bogus'
						, QuoteLine__c=qtLineLst[0].Id, LastFollowupReport__c=followUpReport.Id
						, CreatedByAudit__c=TestDataFactoryUtils.getContextUserId()
						, LastModifiedByAudit__c =TestDataFactoryUtils.getContextUserId());
		insert followupReportSummary;

		FollowupReportSummaryCompController.getFollowupReportSummary(qtLineLst[0].Id);
	}

}