objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>This value will be set based on the IMCD Company of your User.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>Leaving this field empty, will automatically copy the IMCD Company value from the Account.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ImcdCompanyLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to get Imcd Company information - Address, Currency..</description>
        <label>Imcd Company Lookup</label>
        <referenceTo>ImcdCompany__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Global_Bypass_Processes_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global Bypass Control Panel</description>
    <label>Global Bypass Processes Settings</label>
</CustomObject>

objects/ImcdCompany__c.object
<CustomObject>
    <description>Custom Object used to store data specific to each IMCD company (see the IMCD global picklist). It is used (not only) for quote document generation purpose. It is related to user.</description>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <label>IMCD Company</label>
    <nameField>
        <label>IMCD Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMCD Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestCaseTriggerHelper.cls
/******************************************************************************************************************************************************************
 * Author: NC
 * Company: Salesforce
 * Description: Tests for CaseTriggerHelper
 * History :
 ******************************************************************************************************************************************************************/
@IsTest
public class TestCaseTriggerHelper {
    @testSetup static void setup(){
		Global_Bypass_Processes_Settings__c cs = TestDataFactory.createBypassCustomSetting();
        /*Creating 2 distinct random IMCD company values */
        String imcdCompanyTestValue;
        do {
            imcdCompanyTestValue = TestDataFactoryUtils.getRandomPickListValue(new Account(), Label.IMCDCompany_Field_Name);
        } while (imcdCompanyTestValue.indexOf('0') < 3);
        String imcdCompanyTestValue2;
        do {
            imcdCompanyTestValue2 = TestDataFactoryUtils.getRandomPickListValue(new Account(), Label.IMCDCompany_Field_Name);
        } while (imcdCompanyTestValue2.equals(imcdCompanyTestValue) || imcdCompanyTestValue2.indexOf('0') < 3);
        List<String> imcdCompaniesForTest = new List<String>{imcdCompanyTestValue,imcdCompanyTestValue2};
		TestDataFactory.createImcdCompanies(imcdCompaniesForTest);
        System.DEBUG(imcdCompaniesForTest);
    }
    
    @isTest
    public static void isIMCDCompanyLookupSet_onInsert(){
        String imcdCompanyTestValue ;
        List<IMCDCompany__c> existingCompanies = [SELECT ID, Name, IMCDCompany__c FROM IMCDCompany__c];
        imcdCompanyTestValue = existingCompanies[0].IMCDCompany__c;
        
        Case caseToInsert = new Case(IMCDCompany__c = imcdCompanyTestValue);
        
        Test.startTest();
        	insert caseToInsert;
        Test.stopTest();
        
        System.assertEquals(imcdCompanyTestValue, [SELECT IMCDCompanyLookup__r.ImcdCompany__c FROM Case where Id =: caseToInsert.Id][0].IMCDCompanyLookup__r.ImcdCompany__c);
		
    }
    
    @isTest
    public static void isIMCDCompanyLookupSet_onUpdate(){
        String imcdCompanyTestValue ;
        List<IMCDCompany__c> existingCompanies = [SELECT ID, Name, IMCDCompany__c FROM IMCDCompany__c];
        System.debug(existingCompanies);
        imcdCompanyTestValue = existingCompanies[0].IMCDCompany__c;
        String imcdCompanyTestValueToChangeToo = existingCompanies[1].IMCDCompany__c;
        Case caseToInsert = new Case(IMCDCompany__c = imcdCompanyTestValue);
        insert caseToInsert;
        Test.startTest();
        	caseToInsert.IMCDCompany__c = imcdCompanyTestValueToChangeToo;
        	update caseToInsert;
        Test.stopTest();
        
        System.assertEquals(imcdCompanyTestValueToChangeToo, [SELECT IMCDCompanyLookup__r.ImcdCompany__c FROM Case where Id =: caseToInsert.Id][0].IMCDCompanyLookup__r.ImcdCompany__c);
		
    }
}