objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>This value will be set based on the IMCD Company of your User.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ImcdCompany__c.object
<CustomObject>
    <description>Custom Object used to store data specific to each IMCD company (see the IMCD global picklist). It is used (not only) for quote document generation purpose. It is related to user.</description>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <label>IMCD Company</label>
    <nameField>
        <label>IMCD Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMCD Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LOB1__c</fullName>
        <inlineHelpText>Leaving this field empty, will automatically copy the Primary LOB1/2/3 values from the Account</inlineHelpText>
        <label>LOB1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SharingAccess__c.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOB1__c</fullName>
        <label>LOB1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <label>Sharing Access</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sharing Access</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/LOB1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advanced Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Coatings &amp; Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Food</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care and I&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Lubricants</fullName>
    </customValue>
    <customValue>
        <fullName>Other Specialties</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Care</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmaceuticals</fullName>
    </customValue>
    <customValue>
        <fullName>Synthesis</fullName>
    </customValue>
    <masterLabel>LOB1</masterLabel>
</GlobalValueSet>

classes/QueueableOppDeleteSharing.cls
/******************************************************************************************************************************************************************
* Author: Eli Pogorelov
* Company: Salesforce
* Description: Queueable for deleting Sharing based on Opportunity records
* Inputs : Map<String, Map <String, List<SharingAccess__c> > >, Map<String, List<SharingAccess__c> >, Map<String, Map <String, List<SharingAccess__c> > >,
* Map<String, List<SharingAccess__c> >, List<AccountShare>
* Test Class : TestSharingAccessTriggerHelper
* History :
******************************************************************************************************************************************************************/
public without sharing class QueueableOppDeleteSharing implements Queueable
{
    Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessNoPrincipalMap = new Map<String, Map <String, List<SharingAccess__c> > >();
    Map<String, List<SharingAccess__c> > globalSharingAccessesNoPrincipalMap = new Map<String, List<SharingAccess__c> >();
    Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessPrincipalMap = new Map<String, Map <String, List<SharingAccess__c> > >();
    Map<String, List<SharingAccess__c> > globalSharingAccessesPrincipalMap = new Map<String, List<SharingAccess__c> >();

    List<AccountShare> accSharepassedToQueueble = new List<AccountShare>();
    List<OpportunityShare> oppSharepassedToQueueble = new List<OpportunityShare>();

    public QueueableOppDeleteSharing(Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessNoPrincipalMap, Map<String, List<SharingAccess__c> > globalSharingAccessesNoPrincipalMap,
                                    Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessPrincipalMap,Map<String, List<SharingAccess__c> > globalSharingAccessesPrincipalMap,List<AccountShare> accSharepassedToQueueble)
    {
        this.lob1toSharingAccessNoPrincipalMap = lob1toSharingAccessNoPrincipalMap;
        this.globalSharingAccessesNoPrincipalMap = globalSharingAccessesNoPrincipalMap;
        this.lob1toSharingAccessPrincipalMap = lob1toSharingAccessPrincipalMap;
        this.globalSharingAccessesPrincipalMap = globalSharingAccessesPrincipalMap;
        this.accSharepassedToQueueble = accSharepassedToQueueble;
    }

    public void execute(QueueableContext context)
    {
        try
        {
            if (!lob1toSharingAccessNoPrincipalMap.isEmpty())
            {
                Map<Id, List<SharingAccess__c>> accsToShareAccsMap = new Map<Id, List<SharingAccess__c>>();
                Map<Id, List<SharingAccess__c>> oppsToShareAccessMap = new Map<Id, List<SharingAccess__c>>();
                Map<Id, Set<Id>> accIdsToUsrIds = new Map<Id, Set<Id>>();
                Map<Id, Set<Id>> oppIdsToUsrIds = new Map<Id, Set<Id>>();

                Set<String> imcdCompNames = new Set<String>();
                for(map<String, list<SharingAccess__c>> imcdCompanyToShareAccess : lob1toSharingAccessNoPrincipalMap.values())
                {
                    imcdCompNames.addAll(imcdCompanyToShareAccess.keySet());
                }

                List<Opportunity> ShareOppList = new List<Opportunity>([
                        SELECT Id, LOB1__c, AccountId, Account.IMCDCompany__c, Account.ParentId
                        FROM Opportunity
                        WHERE (LOB1__c IN :lob1toSharingAccessNoPrincipalMap.keySet() AND Account.IMCDCompany__c IN : imcdCompNames)]);

                if(!ShareOppList.isEmpty())
                {
                    List<AccountShare> accShareToDelete = new List<AccountShare>() ;
                    List<OpportunityShare> oppShareToDelete = new List<OpportunityShare>() ;
                    //aggregating the Sharing access records related to previously deleted LOB Classifications Records
                    SharingUtils.aggregateRecordsToDelete(ShareOppList, lob1toSharingAccessNoPrincipalMap, accsToShareAccsMap, oppsToShareAccessMap, globalSharingAccessesNoPrincipalMap);

                    if(!accsToShareAccsMap.isEmpty())
                    {   //mapping the users that we need to delete from sharing of Sold To, Regional Accounts
                        SharingUtils.mapSharedUsersToRelObject(accsToShareAccsMap, accIdsToUsrIds);
                        SharingUtils.mapSharedUsersToRelObject(oppsToShareAccessMap, oppIdsToUsrIds);

                        for(AccountShare acShare : SharingUtils.getAccountShares(accIdsToUsrIds,Label.MANUAL_RAW_CAUSE))
                        {
                            if (accIdsToUsrIds.get(acShare.AccountId).contains(acShare.userOrGroupID) )
                            {
                                accShareToDelete.add(acShare);
                            }
                        }
                        for(OpportunityShare opShare : SharingUtils.getOpportunityShares(oppIdsToUsrIds,Label.MANUAL_RAW_CAUSE))
                        {
                            if(oppIdsToUsrIds.get(opShare.OpportunityId).contains(opShare.userOrGroupID) )
                            {
                                oppShareToDelete.add(opShare);
                            }
                        }
                    }
                    if(!oppShareToDelete.isEmpty() || !accShareToDelete.isEmpty())
                    {
                        /*if we are going to hit DML limit we'll insert what possible and pass the remains of the sharing record next queueable to get fresh set of limits*/
                        SharingUtils.combineRemainAndSharingList(accShareToDelete,accSharepassedToQueueble);
                        SharingUtils.checkForDMLlimitAndInsertOrDeleteSharing(accShareToDelete,accSharepassedToQueueble,oppShareToDelete,oppSharepassedToQueueble,false);
                    }
                    else if(oppShareToDelete.isEmpty() && accShareToDelete.isEmpty())
                    {
                        if(accSharepassedToQueueble.size() > 0)
                        {
                            SharingUtils.checkForDMLlimitAndInsertOrDeleteSharingRemains(accSharepassedToQueueble, false);
                        }
                    }
                }
            }
            system.debug('+++QueueableOppDeleteSharing getHeapSize()'+ Limits.getHeapSize());
            //Delete Sharing Accounts and Quotes based on Quotes
            QueueableQuoteDeleteSharing deleteAccAndQuoteSharesBasedQtJob = new QueueableQuoteDeleteSharing(lob1toSharingAccessNoPrincipalMap, globalSharingAccessesNoPrincipalMap,
                    lob1toSharingAccessPrincipalMap,globalSharingAccessesPrincipalMap, accSharepassedToQueueble, oppSharepassedToQueueble);
            if(!Test.isRunningTest())
            {
                System.enqueueJob(deleteAccAndQuoteSharesBasedQtJob);
            }
        }
        catch(Exception ex)
        {
            DebugLog.addException(ex, 'QueueableOppDeleteSharing') ;
        }
    }
}