objects/AccountShiptoAddress__c.object
<CustomObject>
    <description>Custom object which has master/detail relationship with Account.</description>
    <fields>
        <fullName>CountryLabel__c</fullName>
        <label>Country Label</label>
        <length>99</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FinalCountries</valueSetName>
        </valueSet>
    </fields>
    <label>Ship-to Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship-to Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AccountShipToAddressTriggerHelper.cls
/*------------------------------------------------------------
  Author		: Nimil Christopher
  Company		: Salesforce
  Description	: Trigger Helper Class
  Inputs 		: 
  Test Class 	: TestAccountShipToAddressTriggerHelper
  History		: 23/05/2018 created
------------------------------------------------------------*/	
public with sharing class AccountShipToAddressTriggerHelper {
    /*
    * Author: Nimil Christopher
    * Company: Salesforce
    * Description: Sets the Label of the Picklists - Company and IncoTerms as their api and labels are different
    * Inputs : List<AccountShiptoAddress__c>
    * Test Class : TestSbqqQuoteTrigerHelper.isCompanyLabelCopiedAcrossForInsert()
    * Test Class : TestSbqqQuoteTrigerHelper.isCompanyLabelCopiedAcrossForUpdate()
    * History :
    */
    public static void setLabel(List<AccountShiptoAddress__c> newAccountShiptoAddressList){
        AccountShipToAddress__c shipToAddress = new AccountShipToAddress__c();
        Map<String, String> countryPicklistMap = IMCDUtils.getPickListValues(shipToAddress, 'Country__c');
        for(AccountShiptoAddress__c eachAddress : newAccountShiptoAddressList){
            eachAddress.CountryLabel__c = countryPicklistMap.get(eachAddress.Country__c);
        }        
        System.DEBUG('AddresList : ' + newAccountShiptoAddressList);
    }
}