objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>This value will be set based on the IMCD Company of your User.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ImcdCompany__c.object
<CustomObject>
    <description>Custom Object used to store data specific to each IMCD company (see the IMCD global picklist). It is used (not only) for quote document generation purpose. It is related to user.</description>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <label>IMCD Company</label>
    <nameField>
        <label>IMCD Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMCD Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>GroupFlag__c</fullName>
        <description>Identifies a Price Book to be for a Global ERP company. Previous: NOT ( CONTAINS ( $Setup.IntegrationSettings__c.LocalErpComps__c , TEXT ( ImcdCompany__c ) ) )</description>
        <formula>NOT (CONTAINS ( $Setup.IntegrationSettings__c.LocalProductCompanies__c , TEXT ( ImcdCompany__c ) ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Identifies a Price Book to be for a Global ERP company.</inlineHelpText>
        <label>Group Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Alert__c</fullName>
        <description>If empty the products are free to select</description>
        <label>Alert</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AllowedCountries__c</fullName>
        <description>Product allowed countries</description>
        <label>Allowed Countries</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GroupFlag__c</fullName>
        <description>Defines whether this is a Group product. A company number is a string of 5 digits. Formula checks for two aspects of the FullSegmentsNumber to tell it&apos;s Group or Local.</description>
        <formula>NOT (
   AND (
			   	CONTAINS ( FullSegmentsNumber__c , &apos;__&apos;)
				   , ( LEN ( FullSegmentsNumber__c ) - FIND ( &apos;__&apos; , FullSegmentsNumber__c ) ) = 6
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Defines whether this is a Group product</inlineHelpText>
        <label>Group Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ItemStatus__c</fullName>
        <description>Product item status</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>03.Active Pre Sales</fullName>
                    <label>Active Pre Sales</label>
                </value>
                <value>
                    <fullName>04.Active Sales</fullName>
                    <label>Active Sales</label>
                </value>
                <value>
                    <fullName>06.Inactive</fullName>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>01.New</fullName>
                    <label>New</label>
                </value>
                <value>
                    <fullName>07.Obsolete</fullName>
                    <label>Obsolete</label>
                </value>
                <value>
                    <fullName>05.Phase Out</fullName>
                    <label>Phase out</label>
                </value>
                <value>
                    <fullName>02.Temp Pre Sales</fullName>
                    <default>true</default>
                    <label>Temp Pre Sales</label>
                </value>
                <value>
                    <fullName>99.Rejected Temp</fullName>
                    <label>Rejected Temp</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <isActive>false</isActive>
                    <label>10</label>
                </value>
                <value>
                    <fullName>100</fullName>
                    <isActive>false</isActive>
                    <label>100</label>
                </value>
                <value>
                    <fullName>101</fullName>
                    <isActive>false</isActive>
                    <label>101</label>
                </value>
                <value>
                    <fullName>102</fullName>
                    <isActive>false</isActive>
                    <label>102</label>
                </value>
                <value>
                    <fullName>103</fullName>
                    <isActive>false</isActive>
                    <label>103</label>
                </value>
                <value>
                    <fullName>104</fullName>
                    <isActive>false</isActive>
                    <label>104</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <isActive>false</isActive>
                    <label>11</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <isActive>false</isActive>
                    <label>12</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <isActive>false</isActive>
                    <label>13</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <isActive>false</isActive>
                    <label>14</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <isActive>false</isActive>
                    <label>15</label>
                </value>
                <value>
                    <fullName>16</fullName>
                    <isActive>false</isActive>
                    <label>16</label>
                </value>
                <value>
                    <fullName>17</fullName>
                    <isActive>false</isActive>
                    <label>17</label>
                </value>
                <value>
                    <fullName>18</fullName>
                    <isActive>false</isActive>
                    <label>18</label>
                </value>
                <value>
                    <fullName>19</fullName>
                    <isActive>false</isActive>
                    <label>19</label>
                </value>
                <value>
                    <fullName>20</fullName>
                    <isActive>false</isActive>
                    <label>20</label>
                </value>
                <value>
                    <fullName>21</fullName>
                    <isActive>false</isActive>
                    <label>21</label>
                </value>
                <value>
                    <fullName>22</fullName>
                    <isActive>false</isActive>
                    <label>22</label>
                </value>
                <value>
                    <fullName>23</fullName>
                    <isActive>false</isActive>
                    <label>23</label>
                </value>
                <value>
                    <fullName>24</fullName>
                    <isActive>false</isActive>
                    <label>24</label>
                </value>
                <value>
                    <fullName>25</fullName>
                    <isActive>false</isActive>
                    <label>25</label>
                </value>
                <value>
                    <fullName>26</fullName>
                    <isActive>false</isActive>
                    <label>26</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LocalCompanyIndex__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Indexed version of LocalCompany__c</inlineHelpText>
        <label>LocalCompanyIndex</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocalCompany__c</fullName>
        <description>Defines the Company for Non-Group products</description>
        <formula>IF ( GroupFlag__c , &apos;&apos;, RIGHT ( FullSegmentsNumber__c , 5 ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Defines the Company for Non-Group products</inlineHelpText>
        <label>Local Company</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pricipal of Product</description>
        <label>Principal</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You have to select a valid Global principal.</errorMessage>
            <filterItems>
                <field>Account.TF_RecordTypeDeveloperName__c</field>
                <operation>equals</operation>
                <value>Principal_Global</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment4__c</fullName>
        <description>Product segment 4</description>
        <label>Segment 4</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TF_ExcludeSegment4__c</fullName>
        <description>SFDP-988 Extra search</description>
        <label>Exclude Segment 4</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Exclude segment 4</fullName>
                    <default>true</default>
                    <label>Exclude segment 4</label>
                </value>
                <value>
                    <fullName>Only show segment 4</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TempProductFlag__c</fullName>
        <description>Is this a Temp product?</description>
        <formula>ISPICKVAL( ItemStatus__c , &apos;02.Temp Pre Sales&apos; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Temporary Product</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <description>Standard product record type</description>
        <label>Product</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CPQadvancedSearchPlugin.cls
global  class CPQadvancedSearchPlugin implements SBQQ.ProductSearchPlugin{
    
    /*------------------------------------------------------------
        Author:         Wim van Beek
        Company:        Salesforce / NNCourage
        Description:    Will activate an advanced search to find the products and indicate problemes with that products
                        1. Search PBE and products in either standard PB or specific PB
                        2. Some array-processing and checking for allowed countries and de-doubling
                        3. Query 2 to return PriceBookEntries
        Deploy:         Place in 'Product Search Plugin' in 'Plugins' from Package-CPQ

        Source:         https://community.steelbrick.com/t5/Developer-Guidebook/Product-Search-Plugin/ta-p/13626
                        Only section search has been adapted, comments from source still present
        Special         Must be non-blocking and non-error reporting. Empty queries will result in no output

        History
        03-2018     Wim van Beek Initial
        29-6-2018   Wim van Beek, Changed Country-field in Account. Billing=>Shipping. Removed ISOcode translation.
                    Assumtion: Works with ISOcodes only   
        6-7-2018    Wim van Beek, Changed buildup of Quoery in search. 
        18-8-18     Change   TempProductFlag__c for NoActiveProd__c ??
        26-11-2018  Change   Added TF_ExcludeSegment4__c field for selection

    ------------------------------------------------------------*/  
    

    Global class priceBookEntrySelectionClass {
        Public Boolean hasEntry = false;
        Public Set<String>  msg = null; 
        Public id priceBookeEntryId;
        Public String allowedCountries;
    }

    global CPQadvancedSearchPlugin(){
        
    }

    global Boolean isSearchCustom(SObject quote, Map<String,Object> fieldValuesMap){
        return true;
    }   
    global Boolean isFilterHidden(SObject quote, String fieldName){
        return false;
    }   
    global String getFilterDefaultValue(SObject quote, String fieldName){
        return NULL;
    }
    global String getAdditionalSearchFilters(SObject quote, Map<String,Object> fieldValuesMap){
        return NULL;
    }
    // Only use search here
    global List<PricebookEntry> search(SObject quote, Map<String,Object> fieldValuesMap){
        system.debug('------ theSearch '+ fieldValuesMap);
        
        Map<Id, priceBookEntrySelectionClass> priceBookEntryMap = new Map<Id, priceBookEntrySelectionClass>();

        String theCountry ;
        for (Account acc:[SELECT id, BillingCountry, ShippingCountry FROM Account WHERE id =: string.valueof(quote.get('SBQQ__Account__c'))]){
            theCountry = acc.ShippingCountry;
        }
        System.debug('------ theCountry '+ theCountry);
        
        Pricebook2 pricebook ;
        String PBid = string.valueOf(quote.get('SBQQ__PricebookId__c'));
        for (Pricebook2 pb2 :  [SELECT id, ImcdCompany__c,GroupFlag__c  FROM Pricebook2 WHERE id =: PBid ]){
            pricebook = pb2;
        }
        System.debug('------ pricebook '+ pricebook);


        //GET ALL POSSIBLE FILTER FIELDS FROM THE SEARCH FILTER FIELD SET

        List<Schema.FieldSetMember> searchFilterFieldSetFields = SObjectType.Product2.FieldSets.SBQQ__SearchFilters.getFields();

        //GET ALL POSSIBLE FIELDS FROM THE SEARCH RESULTS FIELD SET
        List<Schema.FieldSetMember> searchResultFieldSetFields = SObjectType.Product2.FieldSets.SBQQ__SearchResults.getFields();

        //BUILD THE SELECT STRING
        String selectClause = 'SELECT ';
        // Make sure to include product2 fields in the list if required in the query.
        Set<String> theFieldsSelect = new Set<String>{'id', 'UnitPrice', 'Product2.Segment4__c', 'Product2.GroupFlag__c','Product2.LocalCompany__c','Pricebook2Id', 'Pricebook2.isStandard', 'Product2.ItemStatus__c', 'Product2.AllowedCountries__c'};
        for(Schema.FieldSetMember field : searchResultFieldSetFields){
            theFieldsSelect.add('Product2.'+ field.getFieldPath());
        }

        String where1;
        String where2;

        selectClause += String.join(new List<String>(theFieldsSelect), ', ');

         // Step 1 Temp products or not temp-products
        String whereClause = 'WHERE ((Pricebook2.isStandard = true AND Product2.TempProductFlag__c = false AND CurrencyIsoCode = \'EUR\' ) ';
        whereClause = whereClause + ' OR (Product2.TempProductFlag__c = true AND Pricebook2.isStandard = false)) ';

        // Search in Group or not
        if (pricebook.GroupFlag__c == true){
            whereClause = whereClause +  ' AND  (Product2.TempProductFlag__c = true OR Product2.GroupFlag__c = true ) ' ; 
            whereClause = whereClause +  ' AND  (Pricebook2.isStandard = true OR Pricebook2.GroupFlag__c = true ) ' ;
        } else {                        
            whereClause = whereClause +  ' AND ( Product2.LocalCompanyIndex__c = \'' + pricebook.ImcdCompany__c  + '\' OR Pricebook2Id = \'' + quote.get('SBQQ__PricebookId__c') + '\' ) '  ;
            whereClause = whereClause +  ' AND  (Pricebook2.isStandard = true OR Pricebook2.GroupFlag__c = false ) ' ;
        }

        system.debug('------ whereClause '+ whereClause);

        List<String> wheres = new List<String>();  // Collection of 'AND'-clauses for SOQL-query

        for (String key : fieldValuesMap.keySet()){
            system.debug('------ key '+ key+ ' ==> ' + fieldValuesMap.get(key));
            if (fieldValuesMap.get(key) != null){
                String newWhere ;
                if (key == 'ItemStatus__c'){
                    newWhere = ' Product2.' + key + ' = ' + '\'' + fieldValuesMap.get(key) + '\'';
                    system.debug('------ key '+ key);
                    } else {
                // Assume all key's are fields in Product2
                    if (key == 'Principal__c'){
                        newWhere = ' Product2.' + key + ' = ' + '\'' + fieldValuesMap.get(key) + '\'';
                    } else {
                        if (key == 'TF_ExcludeSegment4__c'){ // New 26-11-2018
                            String choice = String.valueOf(fieldValuesMap.get(Key));
                            if (choice != null ){
                                system.debug('------ choice '+ choice);
                                if (choice == 'Exclude segment 4' ) {
                                    newWhere = ' Product2.Segment4__c = null ';
                                }
                                if (choice == 'Only show segment 4' ) {
                                    newWhere = ' Product2.Segment4__c != null ';
                                }
                            }  
                        } else {
                            newWhere = ' Product2.' + key + ' Like ' + '\'%' + String.escapeSingleQuotes(String.valueOf(fieldValuesMap.get(Key))) + '%\'';
                        }
                    }
                }
                
                system.debug('------ newWhere '+ newWhere);
                if (newWhere != null){
                    wheres.add(newWhere);
                }
            }
        }
 
        for(Schema.FieldSetMember field : searchFilterFieldSetFields){
            if (fieldValuesMap.get(field.getFieldPath()) != null ){
                if(field.getType() ==   Schema.DisplayType.Picklist){
                    wheres.add('  Product2.' + field.getFieldPath() + ' = ' + fieldValuesMap.get(field.getFieldPath()) + ' ');
                }
            }
        }

        if (wheres.size() > 0 ){   // Merge all wheres into one SOQL-where string
        	wheres.add(' Product2.IsActive = true ');  // Defaulted
           	wheres.add(' IsActive = true ');

            whereClause += ' AND  (';
            whereClause += String.join(wheres, ' AND ');
            whereClause += '    )   ';

        } else {
            return new List<PricebookEntry>();  // Empty search because no selections data available
        }

        //BUILD THE QUERY#1

        system.debug('------ selectClause '+ selectClause);
        system.debug('------ whereClause '+ whereClause);
        if (Test.isRunningTest() == true ){whereClause = '';}   // Hate it. Some issue with Pricebook settings. 
                                                                // In a testclass the standardpricebook does not have all functions available 
                                                                // The crossobject search seems to be one of these issues 
        String query = selectClause + ' FROM PricebookEntry  ' + whereClause + ' ORDER BY Product2.Name LIMIT 300 '; // Max 400

        //DO THE QUERY #1
        List<PricebookEntry> pbesQuery = new List<PricebookEntry>();
        pbesQuery = Database.query(query);
        if (pbesQuery.size() == 0 ){return new List<PricebookEntry>();} // Empty search

        Map<Id, String> alertStr = new  Map<Id, String>();

        // Analize results per product. Make sure at the end there is only one pricebookentryId per selectable product
        // Fill alert-field if needed.

        for (PricebookEntry PBE : pbesQuery){
//            system.debug('------ PBE.Product2.Segment4__c '+ PBE.Product2.Segment4__c );
            priceBookEntrySelectionClass PBESC = priceBookEntryMap.get(PBE.Product2Id);
            if (PBESC == null){   // Fill priceBookEntrySelectionClass
                PBESC = new priceBookEntrySelectionClass();
                PBESC.msg = new Set<String>();
                priceBookEntryMap.put(PBE.Product2Id, PBESC);
            }
            PBESC.allowedCountries = PBE.Product2.AllowedCountries__c;
            PBESC.priceBookeEntryId = PBE.id;

            if (theCountry == null && PBESC.allowedCountries != null){
                PBESC.msg.add('Customer needs Sold To Country');
            }

            if (theCountry != null && PBESC.allowedCountries != null){
                if (PBESC.allowedCountries.indexOf(theCountry) == -1){
                    PBESC.msg.add('Invalid for country '+ theCountry);   // Country is required, does not match
                }
            }
        }

        List<Id> pbeIDs = new List<Id>();
        for (priceBookEntrySelectionClass PBESC : priceBookEntryMap.values()){
            pbeIDs.add(PBESC.priceBookeEntryId); // Collect all PriceBookEntriesId
        }

        String newWhereClause = ' WHERE id in ( \''+  String.join( pbeIDs, '\', \'' ) + '\' ) ';
        query = selectClause  + ' FROM PricebookEntry  ' + newWhereClause + ' ORDER BY Product2.Name LIMIT 200';
        System.debug('------ query ' + query);
                    
        List<PricebookEntry> pbesOut ;
        pbesOut = Database.query(query);  // Query #2 width selected id's 
        for (PricebookEntry PBE: pbesOut){  // Add msg to Alert-field
            PBE.UnitPrice = 0;
            List<String> theMsgStr = new List<String>(priceBookEntryMap.get(PBE.Product2Id).msg);
            PBE.Product2.Alert__c = String.join(theMsgStr, ', ');  // Fill alert field.
        }

        return pbesOut;
    }   


    global Boolean isSuggestCustom(SObject quote, Map<String,Object> inputValuesMap){
        return true;
    }

    global Boolean isInputHidden(SObject quote, String input){
        return false;
    }   
    global String getInputDefaultValue(SObject quote, String input){
        return NULL;
    }
    global String getAdditionalSuggestFilters(SObject quote , Map<String,Object> xx){
        return NULL;        
    }
    global list<PricebookEntry> suggest(SObject quote , Map<String,Object> xx){
        return NULL;        
    }   
}