objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>This value will be set based on the IMCD Company of your User.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ImcdCompany__c.object
<CustomObject>
    <description>Custom Object used to store data specific to each IMCD company (see the IMCD global picklist). It is used (not only) for quote document generation purpose. It is related to user.</description>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <label>IMCD Company</label>
    <nameField>
        <label>IMCD Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMCD Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LOB1__c</fullName>
        <inlineHelpText>Leaving this field empty, will automatically copy the Primary LOB1/2/3 values from the Account</inlineHelpText>
        <label>LOB1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Principal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pricipal of Product</description>
        <label>Principal</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You have to select a valid Global principal.</errorMessage>
            <filterItems>
                <field>Account.TF_RecordTypeDeveloperName__c</field>
                <operation>equals</operation>
                <value>Principal_Global</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SharingAccess__c.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOB1__c</fullName>
        <label>LOB1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOB1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrincipalId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Principal</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a Principal Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Principal Global</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>SharingAcees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sharing Access</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sharing Access</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/LOB1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advanced Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Coatings &amp; Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Food</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care and I&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Lubricants</fullName>
    </customValue>
    <customValue>
        <fullName>Other Specialties</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Care</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmaceuticals</fullName>
    </customValue>
    <customValue>
        <fullName>Synthesis</fullName>
    </customValue>
    <masterLabel>LOB1</masterLabel>
</GlobalValueSet>

classes/QueueableOppPrincipalRecalculateSharing.cls
/******************************************************************************************************************************************************************
* Author: Eli Pogorelov
* Company: Salesforce
    * Description: Queueable for recalculation of Sharing based on OpportunityLineItems records
* Inputs : Map<String, Map <String, List<SharingAccess__c> > >, Map<String, List<SharingAccess__c> >, Map<Id,Set<Id>>, List<AccountShare>,
* List<OpportunityShare>, List<SBQQ__Quote__Share>
* Test Class :  TestSharingAccessTriggerHelper
* History :
******************************************************************************************************************************************************************/
public without sharing class QueueableOppPrincipalRecalculateSharing implements Queueable
{
    Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessMap = new Map<String, Map <String, List<SharingAccess__c> > >();
    Map<String, List<SharingAccess__c> > globalSharingAccessesMap = new Map<String, List<SharingAccess__c> >();
    Map<Id,Set<Id>> ownersToAccIds = new Map<Id,Set<Id>>();

    List<AccountShare> accSharepassedToQueueble = new List<AccountShare>();
    List<OpportunityShare> oppSharepassedToQueueble = new List<OpportunityShare>();
    List<SBQQ__Quote__Share> qtSharepassedToQueueble = new List<SBQQ__Quote__Share>();

    public QueueableOppPrincipalRecalculateSharing( Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessMap, Map<String, List<SharingAccess__c> > globalSharingAccessesPrincipalMap, Map<Id,Set<Id>> ownersToAccIds,
            List<AccountShare> accSharepassedToQueueble, List<OpportunityShare> oppSharepassedToQueueble, List<SBQQ__Quote__Share> qtSharepassedToQueueble)
    {
        this.lob1toSharingAccessMap = lob1toSharingAccessMap;
        this.globalSharingAccessesMap = globalSharingAccessesPrincipalMap;
        this.ownersToAccIds = ownersToAccIds;
        this.accSharepassedToQueueble = accSharepassedToQueueble;
        this.oppSharepassedToQueueble = oppSharepassedToQueueble;
        this.qtSharepassedToQueueble = qtSharepassedToQueueble;
    }

    public void execute(QueueableContext context)
    {
        try
        {
            List<AccountShare> accShareLst = new List<AccountShare>();
            List<OpportunityShare> oppShareLst = new List<OpportunityShare>();

            if(!lob1toSharingAccessMap.isEmpty())
            {
                Set<Id> globalPrincipals = new Set<Id>();
                Set<Id> globalPrincipalsForLob = new Set<Id>();
                Set<Id> imcdCompPrincipals = new Set<Id>();
                Set<String> imcdCompNames = new Set<String>();
                Set<String> imcdCompEmptyLobNames = new Set<String>();

                //get the relevant principals Id and IMCD company to agregate the right records for deletion and avoid 50000 DML limit
                if(lob1toSharingAccessMap.containsKey('empty_lob'))
                {
                    for(String imcdComp : lob1toSharingAccessMap.get('empty_lob').keySet() )
                    {
                        for(SharingAccess__c sa : lob1toSharingAccessMap.get('empty_lob').get(imcdComp))
                        {
                            imcdCompPrincipals.add(sa.PrincipalId__c);
                            imcdCompEmptyLobNames.add(sa.IMCDCompany__c);
                        }
                    }
                }

                //get the relevant principals Id to agregate the right records for deletion and avoid 50000 DML limit
                if(globalSharingAccessesMap.containsKey('empty_lob_global'))
                {
                    for(SharingAccess__c sa : globalSharingAccessesMap.get('empty_lob_global'))
                    {
                        globalPrincipals.add(sa.PrincipalId__c);
                    }
                }

                //get the relevant principals Id to agregate the right records for deletion and avoid 50000 DML limit
                for(List<SharingAccess__c> saList : globalSharingAccessesMap.values() )
                {
                    for(SharingAccess__c sa : saList)
                    {
                        globalPrincipalsForLob.add(sa.PrincipalId__c);
                    }
                }
                //get the relevant IMCD Company Id to agregate the right records for deletion and avoid 50000 DML limit
                for(Map <String, List<SharingAccess__c> >  value : lob1toSharingAccessMap.values() )
                {
                    imcdCompNames.addAll(value.keySet());
                }

                List<SharingAccess__c> filteredSaLst = new List<SharingAccess__c>();

                for(OpportunityLineItem oli : [SELECT Id, OpportunityId, Opportunity.LOB1__c, Product2.Principal__c, Opportunity.AccountId, Opportunity.Account.IMCDCompany__c, Opportunity.Account.ParentId
                FROM OpportunityLineItem
                WHERE (Opportunity.LOB1__c IN :lob1toSharingAccessMap.keySet() AND Opportunity.Account.IMCDCompany__c  IN : imcdCompNames) // UC6 lob + company
                OR (Opportunity.LOB1__c IN : globalSharingAccessesMap.keySet() AND Product2.Principal__c IN : globalPrincipalsForLob) // UC2 lob + global
                OR (Product2.Principal__c IN : imcdCompPrincipals  AND Opportunity.Account.IMCDCompany__c IN : imcdCompEmptyLobNames) //UC5 empty lob + company
                OR (Product2.Principal__c IN : globalPrincipals) ]) //UC1 empty lob + global
                {
                    //sharing Account and Opp if LOB1 & IMCDCompany match
                    if(oli.Opportunity.LOB1__c != null)
                    {
                        if (lob1toSharingAccessMap.containsKey(oli.Opportunity.LOB1__c) && lob1toSharingAccessMap.get(oli.Opportunity.LOB1__c).containsKey(oli.Opportunity.Account.IMCDCompany__c))
                        {
                            filteredSaLst = SharingUtils.filterByPrincipal(oli.Opportunity.LOB1__c, oli.Opportunity.Account.IMCDCompany__c, oli, lob1toSharingAccessMap);
                            if(!filteredSaLst.isEmpty())
                            {
                                oppShareLst.addAll(SharingUtils.opportunitySharing(oli.OpportunityId, filteredSaLst, Label.READ_WRITE_ACCESS, Label.MANUAL_RAW_CAUSE));
                                //SharingUtils.debugSharingReason('Opportunity','LOB1 & IMCDCompany match','QueueableOppPrincipalRecalculateSharing',lob1toSharingAccessMap.get(oli.Opportunity.LOB1__c).get(oli.Opportunity.Account.IMCDCompany__c));
                                if(oli.Opportunity.Account.ParentId!=null)
                                {
                                    accShareLst.addAll(SharingUtils.accountSharing(oli.Opportunity.AccountId, oli.Opportunity.Account.ParentId, filteredSaLst, Label.READ_WRITE_ACCESS, Label.NO_ACCESS, Label.MANUAL_RAW_CAUSE,ownersToAccIds));
                                    //SharingUtils.debugSharingReason('Account','sharing the soldTo+C2 LOB1 & IMCDCompany match','QueueableOppPrincipalRecalculateSharing',lob1toSharingAccessMap.get(oli.Opportunity.LOB1__c).get(oli.Opportunity.Account.IMCDCompany__c));
                                }
                                else
                                {
                                    accShareLst.addAll(SharingUtils.accountSharing(oli.Opportunity.AccountId, null, filteredSaLst, Label.READ_WRITE_ACCESS, Label.NO_ACCESS, Label.MANUAL_RAW_CAUSE, ownersToAccIds));
                                    //SharingUtils.debugSharingReason('Account', 'sharing the soldTo LOB1 & IMCDCompany match', 'QueueableOppPrincipalRecalculateSharing', lob1toSharingAccessMap.get(oli.Opportunity.LOB1__c).get(oli.Opportunity.Account.IMCDCompany__c));
                                }
                            }
                        }
                        //Sharing Account and Opp if LOB1 match and SharingAccess record is Global
                        if (globalSharingAccessesMap.containsKey(oli.Opportunity.LOB1__c))
                        {
                            filteredSaLst = SharingUtils.filterByPrincipal(oli.Opportunity.LOB1__c, oli, globalSharingAccessesMap);
                            if(!filteredSaLst.isEmpty())
                            {
                                oppShareLst.addAll(SharingUtils.opportunitySharing(oli.OpportunityId, filteredSaLst, Label.READ_WRITE_ACCESS, Label.MANUAL_RAW_CAUSE));
                                //SharingUtils.debugSharingReason('Opportunity','LOB1 match and SharingAccess record is Global','QueueableOppPrincipalRecalculateSharing',lob1toSharingAccessMap.get(oli.Opportunity.LOB1__c).get(oli.Opportunity.Account.IMCDCompany__c));
                                if(oli.Opportunity.Account.ParentId!=null)
                                {
                                    accShareLst.addAll(SharingUtils.accountSharing(oli.Opportunity.AccountId, oli.Opportunity.Account.ParentId, filteredSaLst, Label.READ_WRITE_ACCESS, Label.NO_ACCESS, Label.MANUAL_RAW_CAUSE,ownersToAccIds));
                                    //SharingUtils.debugSharingReason('Account','sharing the soldTo+C2 LOB1 match and SharingAccess record is Global','QueueableOppPrincipalRecalculateSharing',lob1toSharingAccessMap.get(oli.Opportunity.LOB1__c).get(oli.Opportunity.Account.IMCDCompany__c));
                                }
                                else
                                {
                                    accShareLst.addAll(SharingUtils.accountSharing(oli.Opportunity.AccountId, null, filteredSaLst, Label.READ_WRITE_ACCESS, Label.NO_ACCESS, Label.MANUAL_RAW_CAUSE, ownersToAccIds));
                                    // SharingUtils.debugSharingReason('Account', 'sharing the soldTo LOB1 match and SharingAccess record is Global', 'QueueableOppPrincipalRecalculateSharing', lob1toSharingAccessMap.get(oli.Opportunity.LOB1__c).get(oli.Opportunity.Account.IMCDCompany__c));
                                }
                            }
                        }
                    }
                    //Sharing access without LOB
                    if(lob1toSharingAccessMap.containsKey('empty_lob') && lob1toSharingAccessMap.get('empty_lob').containsKey(oli.Opportunity.Account.IMCDCompany__c))
                    {
                        filteredSaLst = SharingUtils.filterByPrincipal('empty_lob', oli.Opportunity.Account.IMCDCompany__c, oli, lob1toSharingAccessMap);

                        if(!filteredSaLst.isEmpty()) {
                            oppShareLst.addAll(SharingUtils.opportunitySharing(oli.OpportunityId, filteredSaLst, Label.READ_WRITE_ACCESS, Label.MANUAL_RAW_CAUSE));
                            if(oli.Opportunity.Account.ParentId!=null)
                            {
                                accShareLst.addAll(SharingUtils.accountSharing(oli.Opportunity.AccountId, oli.Opportunity.Account.ParentId, filteredSaLst, Label.READ_WRITE_ACCESS, Label.NO_ACCESS, Label.MANUAL_RAW_CAUSE, ownersToAccIds));
                            }
                            else
                            {
                                accShareLst.addAll(SharingUtils.accountSharing(oli.Opportunity.AccountId, null, filteredSaLst, Label.READ_WRITE_ACCESS, Label.NO_ACCESS, Label.MANUAL_RAW_CAUSE, ownersToAccIds));
                            }
                        }
                    }
                    //Sharing access without LOB - Global
                    if(globalSharingAccessesMap.containsKey('empty_lob_global'))
                    {
                        filteredSaLst = SharingUtils.filterByPrincipal('empty_lob_global', oli, globalSharingAccessesMap);
                        if(!filteredSaLst.isEmpty())
                        {
                            oppShareLst.addAll(SharingUtils.opportunitySharing(oli.OpportunityId, filteredSaLst, Label.READ_WRITE_ACCESS, Label.MANUAL_RAW_CAUSE));
                            if(oli.Opportunity.Account.ParentId!=null)
                            {
                                accShareLst.addAll(SharingUtils.accountSharing(oli.Opportunity.AccountId, oli.Opportunity.Account.ParentId, filteredSaLst, Label.READ_WRITE_ACCESS, Label.NO_ACCESS, Label.MANUAL_RAW_CAUSE, ownersToAccIds));
                            }
                            else
                            {
                                accShareLst.addAll(SharingUtils.accountSharing(oli.Opportunity.AccountId, null, filteredSaLst, Label.READ_WRITE_ACCESS, Label.NO_ACCESS, Label.MANUAL_RAW_CAUSE, ownersToAccIds));
                            }
                        }
                    }
                }
            }
            if (!accShareLst.isEmpty() && !oppShareLst.isEmpty())
            {/*if we are going to hit DML limit we'll insert what possible and pass the remains of the sharing records
                next queueable to get fresh set of limits*/
                SharingUtils.combineRemainAndSharingList(accShareLst,accSharepassedToQueueble);
                SharingUtils.combineRemainAndSharingList(oppShareLst,oppSharepassedToQueueble);
                SharingUtils.checkForDMLlimitAndInsertOrDeleteSharing(accShareLst, accSharepassedToQueueble, oppShareLst, oppSharepassedToQueueble, qtSharepassedToQueueble,true);
            }
            // if we only have remains of AccountShare from other queueable and we can insert them all in current transaction
            else
            {
                if(accSharepassedToQueueble.size() > 0 || oppSharepassedToQueueble.size() > 0 || qtSharepassedToQueueble.size() > 0)
                {
                    SharingUtils.checkForDMLlimitAndInsertOrDeleteSharingRemains(accSharepassedToQueueble, oppSharepassedToQueueble, qtSharepassedToQueueble, true);
                }
            }
            system.debug('+++QueueableOppPrincipalRecalculateSharing getHeapSize()'+ Limits.getHeapSize());
            //Sharing Accounts and Quotes based on QuoteLineItems
            if(!Test.isRunningTest())
            {
                QueueableQtPrincipalRecalculateSharing insertAccAndQuoteSharesBasedQtLineJob = new QueueableQtPrincipalRecalculateSharing(lob1toSharingAccessMap, globalSharingAccessesMap,
                        ownersToAccIds, accSharepassedToQueueble, oppSharepassedToQueueble, qtSharepassedToQueueble) ;
                System.enqueueJob(insertAccAndQuoteSharesBasedQtLineJob);
            }
        }
        catch(Exception ex)
        {
            DebugLog.addException(ex, 'QueueableOppPrincipalRecalculateSharing') ;
        }
    }
}