objects/Case.object
<CustomObject>
    <fields>
        <fullName>IMCDCompany__c</fullName>
        <inlineHelpText>Leaving this field empty, will automatically copy the IMCD Company value from the Account.</inlineHelpText>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ImcdCompanyLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to get Imcd Company information - Address, Currency..</description>
        <label>Imcd Company Lookup</label>
        <referenceTo>ImcdCompany__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ImcdCompany__c.object
<CustomObject>
    <description>Custom Object used to store data specific to each IMCD company (see the IMCD global picklist). It is used (not only) for quote document generation purpose. It is related to user.</description>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <label>IMCD Company</label>
    <nameField>
        <label>IMCD Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMCD Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ImcdCompany__c</fullName>
        <description>Imcd Company for this user</description>
        <label>IMCD Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IMCDCompany</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CaseTriggerHelper.cls
public class CaseTriggerHelper {
	/*
    * Author: Nimil Christopher
    * Company: Salesforce
    * Description: Creates a look up relationship to ImcdCompany object based on the IMCD Company value set on the user profile.
    * Inputs : List<Case>
    * Test Class : TestCaseTrigerHelper.isIMCDLookupSetOnCaseForInsertandUpdate()
    * History :
    */
    public static void setIMCDCompanyLookup(List<Case> newCaseList){
        Map<String, Id> IMCDCompaniesMap = new Map<String, Id>();
        Set<String> IMCDCompanies = new Set<String>();
        for(Case eachCaseLine : newCaseList){
            IMCDCompanies.add(eachCaseLine.ImcdCompany__c);
        }
        for(IMCDCompany__c eachCompany : [SELECT ID, ImcdCompany__c FROM IMCDCompany__c WHERE ImcdCompany__c in: IMCDCompanies]){
            IMCDCompaniesMap.put(eachCompany.ImcdCompany__c, eachCompany.Id);
        }
        System.DEBUG('Companies Map : ' + IMCDCompaniesMap);
        for(Case eachCaseRecord : newCaseList){
            if(!(String.isBlank(eachCaseRecord.IMCDCompany__c))){
                if(!(String.isBlank(IMCDCompaniesMap.get(eachCaseRecord.ImcdCompany__c)))){
                    eachCaseRecord.ImcdCompanyLookup__c = IMCDCompaniesMap.get(eachCaseRecord.ImcdCompany__c);    
                }else{
                    DebugLog.addError('[CaseTriggerHelper][setIMCDCompanyLookup] Unable to find corresponding IMCD Company record for Case :' + eachCaseRecord.Id);
                    eachCaseRecord.ImcdCompanyLookup__c.addError('[CaseTriggerHelper][setIMCDCompanyLookup] Unable to find corresponding IMCD Company record for IMCD Company :' + eachCaseRecord.ImcdCompany__c);
                }
            }
        }
    }
}