objects/IntegrationLog__c.object
<CustomObject>
    <description>This object stores records which require integration. The object triggers in turn Outbound Messages when required. The object also acts as mechanism to track records requiring ETL-based integrations for non-group ERP countries.</description>
    <fields>
        <fullName>ContractedPrice__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Target = SBQQ__ContractedPrice__c</description>
        <label>Contracted Price</label>
        <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
        <relationshipLabel>Integration Logs</relationshipLabel>
        <relationshipName>Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Field storing the type of integration event such as &quot;Create Account&quot;, &quot;Create Principal&quot;, &quot;Create Price&quot;.</description>
        <label>Event</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Queued is the initial status. When the Workflow has submitted the Outbound message the status will be set to Message Triggered. Message Delivered will be updated by Talend once the Outbound message is received and queued on the ESB but before being processed. Integration Completed is updated by Talend or the status is set to Integration Failed. Delivery Failed is updated by Salesforce in case a record remained Queued for &gt; 24 hours.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                    <default>true</default>
                    <label>Queued</label>
                </value>
                <value>
                    <fullName>Message Triggered</fullName>
                </value>
                <value>
                    <fullName>Message Delivered</fullName>
                </value>
                <value>
                    <fullName>Integration Completed</fullName>
                </value>
                <value>
                    <fullName>Integration Failed</fullName>
                </value>
                <value>
                    <fullName>Delivery Failed</fullName>
                </value>
                <value>
                    <fullName>Integration Completed (Country not Active)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>INT{000000000}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IntegrationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings and constants for Integration such as Events etc.</description>
    <fields>
        <fullName>EvtCreateContractedPrice__c</fullName>
        <label>Create Contracted Price Event</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Integration Settings</label>
</CustomObject>

classes/IntegrateContractedPrice.cls
/*------------------------------------------------------------	
Author:        Jeroen Burgers	
Company:       Salesforce	
Description:   Integrate Contracted Prices once a Temp product becomes a Sales product
			   Used as part of PB 'Show all versionsDefault Process Builder for Contracted Price'
			   Developed under generic pattern for Invocable methods using Request/Result classes
			   such that it could be possible used as Apex API service.
		       Method IntegrateContractedPrices is bulkified.
Inputs:        InvocableVariable --> productId	
Outputs:	   InvocableVariable --> success, error
Test Class:    TestIntegrateContractedPrice	
User Story:	   https://imcdgroup.atlassian.net/browse/SFDP-610
History	
	05/09/2018	   Created class
	14/09/2018	   Updated, bulkified and tidied-up
------------------------------------------------------------*/	
global class IntegrateContractedPrice {
    
	// defines input variable which can be passed by the process builder.
    global class IntegrateContractedPriceRequest {
		@InvocableVariable(required=true)
		global ID productId;
    }
    
    // defines output variables 
 	global class IntegrateContractedPriceResult {
        @InvocableVariable(required=false)
		global Boolean success;
        
		@InvocableVariable(required=false)
		global String error;
    }
    
    // Custom exception
	class IntegrateContractedPriceException extends Exception {}

	// Invocable method, should be bulkified for List<IntegrateContractgedPriceRequest> size > 1
    @InvocableMethod (label='Integrate Contracted Prices' description='Identifies target contracted price records to be send for integration')
    global static List<IntegrateContractedPriceResult> IntegrateContractedPrices ( List<IntegrateContractedPriceRequest> requests ) {
        List<IntegrateContractedPriceResult> results = new List<IntegrateContractedPriceResult>();
        Set<String> errors = new Set<String>();
        Set<ID> productIds = new Set<ID>();
        
		// fetch all product Ids to set
        for (IntegrateContractedPriceRequest request : requests) {
	        productIds.add(request.productId);
		}

		// Fetch Event (as custom setting)        
        String event = IntegrationSettings__c.getInstance(UserInfo.getUserId()).EvtCreateContractedPrice__c;
		List<IntegrationLog__c> lstIntLog = new List<IntegrationLog__c>();
        
		// Fetches all Contracted price record for the Set of productIds
        // SBQQ__EffectiveDate__c / SBQQ__ExpirationDate__c are irrelevant, prices to be integrated regardless
        // SOQL should typically return just few records as Temp products aren't used in many quotes. 
        // Add IntegrationLog records to list
        for (SBQQ__ContractedPrice__c price : [SELECT Id FROM SBQQ__ContractedPrice__c 
                                                 WHERE SBQQ__Product__c IN :productIds]) {
			lstIntLog.add(new IntegrationLog__c (ContractedPrice__c  = price.Id, Status__c = 'Queued', Event__c = event) );
        }

		// create result object
        IntegrateContractedPriceResult result = new IntegrateContractedPriceResult();        
        
		// Use Database class and Saveresult. 
		Database.SaveResult[] lstSrInt = Database.insert(lstIntLog, false); //allow partial succes
        
		// Iterate through each returned result
		for (Database.SaveResult srInt : lstSrInt) {

            if (!srInt.isSuccess()) {
        		// Operation failed, get Errors
        		Database.Error err = srInt.getErrors()[0];	
				String error = '[IntegrateContractedPrice][IntegrateContractedPrice] An error has occurred insert IntegrationLog__c records.\n'
					+ err.getStatusCode() + ': ' + err.getMessage() + '\n'
					+ 'Fields affected: ' + + err.getFields();
				errors.add (error); // add to set
			}
 		}
        
        String debugErrors = '';
        for (String error : errors) {
            debugErrors += error;
        }
        
        // write list of errors to debug log (if any)
        if (!String.isBlank (debugErrors)) {
            DebugLog.addError(debugErrors);
            result.success = false;
            result.error = debugErrors;
        }
        
		results.add (result);
		return results;

    }
}