objects/IntegrationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings and constants for Integration such as Events etc.</description>
    <fields>
        <fullName>EvtCreateContractedPrice__c</fullName>
        <label>Create Contracted Price Event</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EvtCreateSoldTo__c</fullName>
        <label>Create Customer (Sold-to) Event</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EvtCreateTempProduct__c</fullName>
        <label>Create Temp Product Event</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocalErpComps__c</fullName>
        <description>Comma-separated list of countries which are using local erp.</description>
        <label>Local ERP Companies</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Recalculations_Per_Hour__c</fullName>
        <description>The maximum number of Quotes that will get resubmitted for calculation per hour</description>
        <label>Quote Recalculations Per Hour</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>stdPricebookId__c</fullName>
        <label>Standard Price Book Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Integration Settings</label>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
</CustomObject>

classes/TestQuoteThrottledRecalculate_Batch.cls
@isTest
global class TestQuoteThrottledRecalculate_Batch {


        @isTest static void testBatch(){

        // Create custom setting record
        IntegrationSettings__c intSetting = new IntegrationSettings__c(Quote_Recalculations_Per_Hour__c = 2500
                                                                      ,EvtCreateContractedPrice__c = 'Test1'
                                                                       ,EvtCreateSoldTo__c = 'Test2'
                                                                       ,EvtCreateTempProduct__c  = 'Test3'
                                                                       ,LocalErpComps__c = 'Test5'
                                                                       ,stdPricebookId__c = 'Test6');
         insert intSetting;
       
        // Create a set of test data
        List<Account> soldToAccounts = TestDataFactory.createAccounts(1, Label.Customer_Sold_To_Account_Record_Type, TestDataFactoryUtils.getContextUserId(), '79100');
            soldToAccounts.addAll(TestDataFactory.createAccounts(1, Label.Customer_Sold_To_Account_Record_Type, TestDataFactoryUtils.getContextUserId(), '13100'));
           
        list<SBQQ__Quote__c> qtLst = TestDataFactory.returnQuotes(1, soldToAccounts[0], new List<String>{'Coatings & Construction'});
        qtLst[0].TF_MigrationRecalcNeeded__c=TRUE;
        insert qtLst;

        // Run the batch
      	Test.startTest();
      	Database.executeBatch(new QuoteThrottledRecalculate_Batch());
      	Test.stopTest();

        // Assert the results
       SBQQ__Quote__c[] testQuote = [select id,TF_MigrationRecalcNeeded__c from SBQQ__Quote__c];
       system.assertEquals(FALSE,testQuote[0].TF_MigrationRecalcNeeded__c);

    }

}