objects/SharingAccess__c.object
<CustomObject>
    <fields>
        <fullName>PrincipalId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Principal</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a Principal Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Principal Global</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>SharingAcees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserDisplayName__c</fullName>
        <formula>UserId__r.LastName + &apos;, &apos; + UserId__r.FirstName + &apos; (&apos; + Id + &apos;)&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User Display Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SharingAcees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bypassEditValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>for bypassing prevent_Editing_Records VR rule in SharingAccess trigger</description>
        <label>bypassEditValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <label>Sharing Access</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sharing Access</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SharingAccessTriggerHelper.cls
/******************************************************************************************************************************************************************
 * Author: Eli Pogorelov
 * Company: Salesforce
 * Description: Event Handler SharingAccessTrigger
 * Inputs :
 * Test Class :
 * History :
 ******************************************************************************************************************************************************************/
public without sharing class SharingAccessTriggerHelper
{
    /******************************************************************************************************************************************************************
    * Author: Eli Pogorelov
    * Company: Salesforce
    * Description: Changes the name of the SharingAccess record according to UserDisplayName__c field on SharingAccess record insert,
    * Inputs : List<SharingAccess__c>, Map<Id,SharingAccess__c>
    * Test Class :
    * History :
    ******************************************************************************************************************************************************************/
    public static void updateRecordName(List<SharingAccess__c> newSharingAccessList)
    {
        try
        {
            List<SharingAccess__c> saToInsertList = new List<SharingAccess__c>();
            for(SharingAccess__c sa : newSharingAccessList)
            {
                SharingAccess__c saTemp = new SharingAccess__c();
                saTemp = sa.clone(true,true,true,true);
                saTemp.bypassEditValidationRule__c = true;
                saTemp.Name = sa.UserDisplayName__c;
                saToInsertList.add(saTemp);
            }
            if(!saToInsertList.isEmpty())
            {
                update saToInsertList;
            }
        }
        catch(Exception ex)
        {
            DebugLog.addException(ex, 'SharingAccessTriggerHelper') ;
        }
    }

    /******************************************************************************************************************************************************************
    * Author: Eli Pogorelov
    * Company: Salesforce
    * Description: Updates sharing for Accounts, Opportunities, Quotes, OpportunityLineItems, QuoteLineItems on insert of SharingAccess record
    * Inputs : List<SharingAccess__c>
    * Test Class :
    * History :
    ******************************************************************************************************************************************************************/
    public static void recalculateOnInsertSharing(List<SharingAccess__c> newSharingAccessList)
    {
        try
        {
             List<SharingAccess__c> principalSaList = new List<SharingAccess__c>();
             List<SharingAccess__c> nonPrincipalSaList = new List<SharingAccess__c>();

             //dividing the sharing access by principal
             SharingUtils.divideByPrincipal(newSharingAccessList,principalSaList, nonPrincipalSaList);
             // get Owners to Accounts Id's to avoid sharing the Account to the owner
             Set<Id> relUserId = new Set<Id>();
             for(SharingAccess__c sa : newSharingAccessList)
             {
                 relUserId.add(sa.UserId__c);
             }
             Map<Id,Set<Id>> ownersToAccsMap = SharingUtils.mapOwnersToAcoountAccountsByIds(relUserId);

             Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessNoPrincipalMap = new Map<String, Map <String, List<SharingAccess__c> > >();
             Map<String, List<SharingAccess__c> > globalSharingAccessesNoPrincipalMap = new Map<String, List<SharingAccess__c> >();

             //mapping principalId__c == NULL Sharing Access records by LOB1 keys and IMCDCompany and creating the global Sharing Access table
             SharingUtils.mappingSharingAccessTable(nonPrincipalSaList, lob1toSharingAccessNoPrincipalMap, globalSharingAccessesNoPrincipalMap);

             Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessPrincipalMap = new Map<String, Map <String, List<SharingAccess__c> > >();
             Map<String, List<SharingAccess__c> > globalSharingAccessesPrincipalMap = new Map<String, List<SharingAccess__c> >();

             //mapping principalId__c != NULL Sharing Access records by LOB1 keys and IMCDCompany and creating the global Sharing Access table
             SharingUtils.mappingSharingAccessTable(PrincipalSaList, lob1toSharingAccessPrincipalMap, globalSharingAccessesPrincipalMap);

            /*Sharing Accounts,Opportunities Quotes based on rules for AccountLob,Opportunity,Quote,OpportunityLineItem,QuoteLineItem queueable jobs are chained
            in this order, parent is : QueueableAccLobRecalculateSharing*/
            QueueableAccLobRecalculateSharing insertAccSharesBasedLobJob = new QueueableAccLobRecalculateSharing(lob1toSharingAccessNoPrincipalMap, globalSharingAccessesNoPrincipalMap, ownersToAccsMap,
            lob1toSharingAccessPrincipalMap, globalSharingAccessesPrincipalMap) ;
            if(!Test.isRunningTest())
            {
                System.enqueueJob(insertAccSharesBasedLobJob);
            }
        }
        catch(Exception ex)
        {
            DebugLog.addException(ex, 'SharingAccessTriggerHelper') ;
        }
    }

   /******************************************************************************************************************************************************************
   * Author: Eli Pogorelov
   * Company: Salesforce
   * Description: Deletes sharing for Accounts, Opportunities, Quotes, OpportunityLineItems, QuoteLineItems on delete of SharingAccess record
   * Inputs : List<SharingAccess__c>
   * Test Class :
   * History :
   ******************************************************************************************************************************************************************/
    public static void recalculateOnDeleteSharing( List<SharingAccess__c> oldSharingAccList)
    {
        try
        {
            List<SharingAccess__c> principalSaList = new List<SharingAccess__c>();
            List<SharingAccess__c> nonPrincipalSaList = new List<SharingAccess__c>();

            //dividing the sharing access by principal
            SharingUtils.divideByPrincipal(oldSharingAccList, principalSaList, nonPrincipalSaList);

            if (oldSharingAccList != null && !oldSharingAccList.isEmpty())
            {
                Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessNoPrincipalMap = new Map<String, Map <String, List<SharingAccess__c> > >();
                Map<String, List<SharingAccess__c> > globalSharingAccessesNoPrincipalMap = new Map<String, List<SharingAccess__c> >();

                //mapping principalId__c == NULL Sharing Access records by LOB1 keys and IMCDCompany and creating the global Sharing Access table
                SharingUtils.mappingSharingAccessTable(nonPrincipalSaList, lob1toSharingAccessNoPrincipalMap, globalSharingAccessesNoPrincipalMap);

                Map<String, Map <String, List<SharingAccess__c> > > lob1toSharingAccessPrincipalMap = new Map<String, Map <String, List<SharingAccess__c> > >();
                Map<String, List<SharingAccess__c> > globalSharingAccessesPrincipalMap = new Map<String, List<SharingAccess__c> >();

                //mapping principalId__c != NULL Sharing Access records by LOB1 keys and IMCDCompany and creating the global Sharing Access table
                SharingUtils.mappingSharingAccessTable(PrincipalSaList, lob1toSharingAccessPrincipalMap, globalSharingAccessesPrincipalMap);

                /*Delete Sharing Accounts based AccountLob,Opportunity,Quote,OpportunityLineItem,QuoteLineItem queueable jobs are chained
                in this order, parent is : QueueableAccLobDeleteSharing*/
                QueueableAccLobDeleteSharing deleteAccSharesBasedLobJob = new QueueableAccLobDeleteSharing(lob1toSharingAccessNoPrincipalMap, globalSharingAccessesNoPrincipalMap,
                        lob1toSharingAccessPrincipalMap, globalSharingAccessesPrincipalMap);
                if(!Test.isRunningTest())
                {
                    System.enqueueJob(deleteAccSharesBasedLobJob);
                }
            }
        }
        catch (Exception ex)
        {
            DebugLog.addException(ex, 'SharingAccessTriggerHelper');
        }
    }
}